### ISSUE TITLE
egress router ServiceDictHandler check service_url in header

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#1006]
ServiceDictHandler currently return STATUS_INVALID_REQUEST_PATH is there is serviceId-path match.
We need check service_url  first before  return STATUS_INVALID_REQUEST_PATH

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [egress router ServiceDictHandler check service_url in header light-4j master](https://trello.com/c/1BOqkIxe/1133-egress-router-servicedicthandler-check-serviceurl-in-header-light-4j-master)
