### ISSUE TITLE
client module re-organize and move some features from light-consumer-4j to client module directly 

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#1015]
client module re-organize
move some features from light-consumer-4j to client module directly to avoid customer application depend on both client module and light-consumer-4j 
document some detail and usage info on readme file

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [client module re-organize and move some features from light-consumer-4j to client module directly light-4j master](https://trello.com/c/95lunwx2/1153-client-module-re-organize-and-move-some-features-from-light-consumer-4j-to-client-module-directly-light-4j-master)
