### ISSUE TITLE
Router config enhancement to allow hostWhiteList to set default value

### ISSUE THREAD

**Issue by GavinChenYan** [networknt/light-4j#1023]
Current set for RouterConfig object is not easy to extend and can not have default value for hostWhiteList

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Router config enhancement to allow hostWhiteList to set default value light-4j master](https://trello.com/c/S3blIsQR/1164-router-config-enhancement-to-allow-hostwhitelist-to-set-default-value-light-4j-master)

**Comment by stevehu** [comment]
While building a new snapshot version, I found that the light-router is broken due to this change. Here is the error. 

```
[ERROR] /home/steve/releassnapshot_2_0_x/light-router/src/test/java/com/networknt/router/HostWhitelistTest.java:[37,33] incompatible types: java.lang.String[] cannot be converted to java.util.List<java.lang.String>

```

**Comment by GavinChenYan** [comment]
The light-router PR merged. I think we can close this issue.
@stevehu  Please confirm

**Comment by stevehu** [comment]
Yes. Closed.
