### ISSUE TITLE
correct request too big message, and change the default body buffer size same as server buffer size  

### ISSUE THREAD

**Issue by GavinChenYan** [networknt/light-4j#1026]
current if the user request payload too big (>16K), user will get error message:
ERR10015:
  statusCode: 400
  code: ERR10015
  message: CONTENT_TYPE_MISMATCH
  description: Content type in header %s doesn't match the body. The body might be trucated due to bufferSize to small in client.xml

But actually, the config is on server.yml

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [correct request too big message, and change the default body buffer size same as server buffer size light-4j master](https://trello.com/c/CQf1v4zk/1196-correct-request-too-big-message-and-change-the-default-body-buffer-size-same-as-server-buffer-size-light-4j-master)
