### ISSUE TITLE
Transform List to Set for Better Performance

### ISSUE THREAD

**Issue by FastAtlas** [networknt/light-4j#1029]
Hi,
We find that the List allocated at line 85 in the function `isExclusionConfigFile` is only used to check whether an element is stored in the container. The method `contains` of a list runs in linear time complexity. We notice that the `exclusionFileList` is maintained in the HashMap `exclusionMap`, which maps a string object to an object.

To achieve the same functionality, maybe a `HashSet` can provide a more efficient implementation. We can just construct a HashSet and maintain it in the HashMap `exclusionMap`. When we invoke the function `isExclusionConfigFile`, we only need to take amortized O(1) time to maintain the map and invoke the `contains` method of `HashSet`.

We discovered this inefficient usage of containers by our tool Ditto. The patch is submitted in #1028 . Could you please check and accept it? We have tested the patch on our PC. The patched program works well. Of course, it would be better to change `EXCLUSION_CONFIG_FILE_LIST` to `EXCLUSION_CONFIG_FILE_Set`. Anyway, the name does not affect the performance anymore.

Bests

Ditto

**Comment by stevehu** [comment]
The code deals with the configuration only, and the number of entries is minimum. The PR has a conflict that cannot be resolved at the moment. I would close this issue and leave the code without any optimization.
