### ISSUE TITLE
Default config value cannot be empty enhancment

### ISSUE THREAD

**Issue by GavinChenYan** [networknt/light-4j#1035]
Currently if the config vaue default is empty, for example:

requestTimeoutMs: ${requestTimeoutMs:}

API server cannot start and have error below:

com.networknt.config.ConfigException: "${requestTimeoutMs:}" appears in config file cannot be expanded

We should allow empty default config and set the config value to null

**Comment by stevehu** [comment]
We do recommend our customers to use default value in the config file template, but it is not possible in some cases as the default value will implicitly creating/allocating some resources. For example, the consumer group id of Kafka etc. We can ask users to set null for the default; however, it would be best to handle it in the framework. I think it is the right thing to do and the impact for the existing applications would be minimum.

**Comment by GavinChenYan** [comment]
Add a config value in he config.yml file for user to indicator if the api allow default value is empty:

**Comment by stevehu** [comment]
This is a much better idea. Most users do want to see the exception to force them to fix the configuration errors. For users who have this flag enabled, they know what they are doing.
