### ISSUE TITLE
Utility methods in server project for accessing path variables

### ISSUE THREAD

**Issue by sachinwalia2k8** [networknt/light-4j#104]
Although light-4j uses undertow internally but I believe it might be a good idea to add some utility methods to extract query params, path params etc. There is a project here on github where such kind of four utility classes exists that may hide little bit of boilerplate code. 

https://github.com/StubbornJava/StubbornJava/tree/master/stubbornjava-undertow/src/main/java/com/stubbornjava/undertow/exchange

Not sure about the license though if MIT license is interoperable with ASL.

**Comment by stevehu** [comment]
@sachinwalia2k8 Excellent findings. I was constantly asked to provide something like that as majority our developers have JAXRS background and not comfortable with exchange APIs. It is in MIT license and we can use it freely. I will take a look and migrate useful utilities. Thanks.

**Comment by sachinwalia2k8** [comment]
I have ported some of the above mentioned methods to my codebase. However I think it would make sense for this to be part of light4j framework. Which project within light4j should logically house these classes? Also do I need to add any attribution to the original author when porting it to light4j?

**Comment by stevehu** [comment]
Handler module is the best place as it has existing dependency on Undertow. If you port the code, please put the original author(s) and yourself as @author. This is the way to pay respect to the original authors and contributors. Thanks.

**Comment by stevehu** [comment]
@sachinwalia2k8 Thanks for the pull request. I will change the package name a little so that it can blend into the existing code.

**Comment by shahrk** [comment]
Can you refer me to any documentation for extracting path params & request body?

**Comment by stevehu** [comment]
@shahrk The information is scattered in several links and I will put them together for users to write business handlers. Should be done today or tomorrow. Thanks a lot for raising the question.

**Comment by stevehu** [comment]
@shahrk Please take a look at this document and let me know if there is anything missing. Thanks.

https://doc.networknt.com/concern/business-handler/
