### ISSUE TITLE
How to read JSON body from an Http POST call

### ISSUE THREAD

**Issue by sachinwalia2k8** [networknt/light-4j#105]
I am trying to use this method to read JSON body from a handler that is coming as part of API call. I followed the method from this sample but getting Null output always.
`https://github.com/networknt/light-example-4j/blob/bfd52eedb10f1ba2808088c90c189c23ed6bddda/eventuate/account-management/account-service/src/main/java/com/networknt/eventuate/account/command/handler/OpenAccountPostHandler.java`

Here is the snippet of my code:

```
Map s = (Map)exchange.getAttachment(BodyHandler.REQUEST_BODY);
String json = objectMapper.writeValueAsString(s);
LoginRequest loginRequest = objectMapper.readValue(json, LoginRequest.class);
```
Both Map and String comes out as null.

Here is my curl call:

`curl -X POST -d '{"username":"test","password":"test"}' -H "Accept: application/json" -H "Content-type: application/json" http://localhost:8020/api/user/login -v
`

Do you think I am missing something here?

thanks.

**Comment by stevehu** [comment]
The input seems correct as you have application/json as content type. Do you have BodyHandler in you request chain? It is the hander that is responsible for consuming the body stream and convert it into a list/map and attached to the exchange. If your code is open sourced, I can help to take a look.

**Comment by stevehu** [comment]
Also, have you tried use postman? Sometime, curl is too easy to make mistakes. The following is one of my examples in curl. 

```
curl -X POST \
  https://localhost:8080/v1/postData \
  -H 'content-type: application/json' \
  -d '{"key":"key1", "value": "value1"}'

```

**Comment by sachinwalia2k8** [comment]
I tried above request as well. It is failing with same error. Do I need to do something additional to have BodyHandler in my request chain. I thought it should work since the example link is also not doing anything extra.

**Comment by sachinwalia2k8** [comment]
Ok. I got it working. I was actually missing the file "com.networknt.handler.MiddlewareHandler" with required middlewares (BodyHandler) and that was causing the exception.

**Comment by sachinwalia2k8** [comment]
I think it may be a good idea to have a tutorial where person who is creating project from scratch (without using any examples) should know what all is needed to get basic things up and running.

**Comment by stevehu** [comment]
The easy way to start a project would be from light-codegen with a swagger specification. Of course, for some users who wants to dig deeper into Undertow features, starting from scratch is an option. I will write something up once I have time; however, it will be great if you could spend some time to write down your experience. I would be happy to accept a PR :)

**Comment by sachinwalia2k8** [comment]
Closing this issue.

**Comment by hitesh22b** [comment]
> I think it may be a good idea to have a tutorial where person who is creating project from scratch (without using any examples) should know what all is needed to get basic things up and running.

Exactly @stevehu the documentation should be newbie friendly, with a simple CRUD and then digging more.
