### ISSUE TITLE
ClassCastException in maskList method fix in light-4j version 1.6.X

### ISSUE THREAD

**Issue by jaydeepparekh1311** [networknt/light-4j#1055]
There was an issue #942 raised related to handling one element in an array for masking.  PR #945 was created for the same and the fix was included in the subsequent light-4j version `2.0.27`.

Our client, who is using the light-4j `1.6.X` version, has raised exactly the same issue. The fix done for #942 needs to be applied and pushed into the upcoming light-4j `1.6.X` version.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ClassCastException in maskList method fix in light-4j version 1.6.X light-4j 1.6.x](https://trello.com/c/F3knmP7l/1321-classcastexception-in-masklist-method-fix-in-light-4j-version-16x-light-4j-16x)

**Comment by stevehu** [comment]
@jaydeepparekh1311 @jsu216 After this issue is merged, do we have any pending issues for 1.6.x? If not, we can start the release process. Thanks.

**Comment by stevehu** [comment]
release 1.6.37 is published. 
https://github.com/networknt/light-4j/releases/tag/1.6.37
