### ISSUE TITLE
Upgrade dependency versions for commons lang + deprecate commons-codec

### ISSUE THREAD

**Issue by sachinwalia2k8** [networknt/light-4j#106]
I see that some project still refers old version of apache commons lang 2.x. This not only is unnecessary but will also increase the binary size of Jar file. 

following is one such reference:
`<version.commons-lang>2.6</version.commons-lang>
`
`https://github.com/networknt/light-4j/search?utf8=%E2%9C%93&q=commons.lang&type=Code
`
Also searching Base64 reveals the usage from both commons-codec as well as java.util.Base64. I think it'd be a good idea to get rid of commons-codec.

`https://github.com/networknt/light-4j/search?utf8=%E2%9C%93&q=Base64&type=
`

**Comment by stevehu** [comment]
You are right. We need to clean up the dependencies. One of the design goal is smaller footprint so that it is easy to be deployed on the cloud environment. I will review these dependencies once finish the current task. Thanks a lot for your help.

**Comment by sachinwalia2k8** [comment]
@stevehu I have sent a pull request to upgrade to commons-lang3 as well as various other dependencies. Moreover I've added mavens version plugin to root project so that periodically it can be checked which all other dependencies have newer version available in maven central. Please review and merge if it looks fine.
