### ISSUE TITLE
Add new filters on logger content handler

### ISSUE THREAD

**Issue by GavinChenYan** [networknt/light-4j#1061]
Currently in the LoggerGetLogContentsHandler, it include two filter parameters:
Log Start time, Log End time.

Add two more filter (optional) to help user to control the log content dsiplay:

Log Name
Log Level

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add new filters on logger content handler light-4j master](https://trello.com/c/fJeBPRgz/1331-add-new-filters-on-logger-content-handler-light-4j-master)
