### ISSUE TITLE
Upgrade to Undertow 1.4.20.Final

### ISSUE THREAD

**Issue by sachinwalia2k8** [networknt/light-4j#108]
Upgrade to Undertow 1.4.20.Final

**Comment by stevehu** [comment]
We upgraded to Undertow 1.4.19.Final recently to resolve an HTTP 2.0 issue and still need to make sure it is stable. There are clients using the framework so, any update must be carefully planned. I will review the release notes of 1.4.20.Final and see if anything is important. Also, we are working on the Jenkins build process and it will help us to change something across multiple repositories. Let's do that step by step as we don't have extra resources. I would be happy if you could help to fork it and try it out and give me a pull requests as the changes must be cross at least 10 more repos. Thanks.

**Comment by sachinwalia2k8** [comment]
sure will test it out locally.

**Comment by stevehu** [comment]
I have merged the light-4j pull request and will work on other repos and release another version once all done. Thanks a lot for your help.

**Comment by sachinwalia2k8** [comment]
@stevehu I have been using a fork with 1.4.20.Final and haven't seen any issue. Will send a pull request tonight.
