### ISSUE TITLE
How to create singleton if one bean depends on another via YML file

### ISSUE THREAD

**Issue by sachinwalia2k8** [networknt/light-4j#109]
I have a following situation:
1. Need to dynamically create HikariDatasource class based on dynamic yaml file.
2. Need to inject this datasource inside a singleton -- DatabaseFacade that abstracts DB operations.

Programmatically I've done by lot of static initialization but it doesn't seem elegant. Is this something that is achievable via service.yml considering I still have to create DataSource programmatically.

thanks.

**Comment by stevehu** [comment]
That is exact what service module is designed for. Take a look at this example on how to switch between Oracle, Postgres and Mysql.

https://networknt.github.io/light-rest-4j/tutorial/database/

**Comment by sachinwalia2k8** [comment]
thanks. this was helpful.

**Comment by acmeguy** [comment]
The link above no longer works.

**Comment by NicholasAzar** [comment]
@acmeguy Does the database section of the following link help? https://doc.networknt.com/example/
