### ISSUE TITLE
Exception Handler enhancement to allow customer to add exception processor.

### ISSUE THREAD

**Issue by GavinChenYan** [networknt/light-4j#1114]
Currently light-4j ExceptionHandler only handle several framework defined exception:

ApiException
FrameworkException
ClientException

Normally API will have project define exception by itself. In this case, we still need handle exception on each handler.

The better way will be define centralized exception handler/processor, and we can leverage the  ExceptionHandler  to handler user defined processor.

**Comment by stevehu** [comment]
@GavinChenYan we have a branch for this issue and it was not merged. I think we have discussed this issue and decide to keep the existing decentralized implementation due to the context info locally. Can we close this issue and remove the branch? Thanks.

**Comment by stevehu** [comment]
The PR is not merged, as we found some use cases that are not covered.
