### ISSUE TITLE
Example of file upload via light4j

### ISSUE THREAD

**Issue by sachinwalia2k8** [networknt/light-4j#115]
Since we are dealing with lower level internals of undertow so it'll be a good idea to see such an example.

**Comment by stevehu** [comment]
@sachinwalia2k8 There is a real example that we use to upload files in light-codegen/codegen-web module. 

https://github.com/networknt/light-codegen/blob/master/codegen-web/src/main/java/com/networknt/codegen/handler/ValidateUploadFileHandler.java
