### ISSUE TITLE
undertow's ExchangeCompletionListener

### ISSUE THREAD

**Issue by yibogithub** [networknt/light-4j#1169]
Hi team,

We use 1.6.x running into a situation where some of our existing code relies on an ExchangeCompletionListener being executed on the handler chain thread. We use a slf4j's MDC in a callback listener and expect it to be a continuation of that on the handler chain thread producing logs with the right MDC values.

While it does not look right to me, it actually worked. I expect the listener being executed on its own thread or a shared thread managed by undertow; but a completion listener of ours is indeed executed on the same thread thus inheriting the right MDC values.

I am not super sure how this could have happened. At the moment It seems to me an explicit call to exchange.endExchange() might have been the cause.

This is not an light4j issue but I tend to think one should not expect an ExchangeCompletionListener being executed on the handler chain thread.

Thanks!

**Comment by stevehu** [comment]
@yibogithub Nice observation. The listeners are indeed called from the same thread, and there is no multi-thread issue. Each middleware handler can register a listener to the exchange, and the exchange will call all the listeners in a chain pattern after the exchange ends. You can call endExchange or send a response to the client to end the exchange; then, all the registered listeners will be invoked one by one. At the time the listeners are invoked, all middleware handlers are done, and the exchange calls the listeners in sequence, so there shouldn't be any thread issue. This is a good design as we can still use the MDC :)

**Comment by stevehu** [comment]
While working with other team members, we realized that we should always call the endExchange when returning the error messages. Just FYI.
