### ISSUE TITLE
enhance the rate limit to support sliding window and limit based on IP and client_id

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#1178]
The current rate limit is based on the concurrent model. I can set how many concurrent requests can pass through. This works if the backend service is slow. For faster backend service or business handler in the same instance, even we set with only one concurrent request, the server can still handle thousands of requests per second. And this behaviour can not pass the penetration test from one of our customers to use the light-gateway. 

Here are the features we want to add to the new implementation. 

1. allow set up rate limiting based on the time slot. For example, 10 requests per minute or 100 requests per hour, etc.
2. guarantee requests to be processed as fast as possible. (Leaky bucket is not meeting this requirement)
3. need to avoid spike of requests (Fixed window is not meeting this requirement)
4. can set rate limit at server level or IP level or client_id (from JWT) level. For example, each client can send 10 requests per minute.
5. can set the rate limit differently based on client_id to give priority client more throughput than others. For example, client A can send 100 requests per minute and all others can send only 10 requests per minute. 

Given the above requirement, I think we should use the sliding window. 
https://medium.com/@NlognTeam/design-a-scalable-rate-limiting-algorithm-system-design-nlogn-895abba44b77

When IP is used, we can put the rate limit handler at the beginning of the chain. When client_id is use, we must put the rate limit handler after the JwtVerifier before the validation. 

#############

Had a discussion with the users and we need to add the following features. 

1. If the server is selected as a key, we cannot allow the user to select quota which is the second part of the rate limit. Otherwise, the server will not respond to any client after the quota is exceeded. 
2. We need to create a key resolver as they are many ways to identify the client or address. For example, the client_id might be in the JWT token, in the header if JWT is not supported, in the query parameter, etc.
3. When the address is used as the key, we also need to check the original IP in the header if the request is from a reverse proxy like Akamai. 
4. We need to add the rate limit response header based on this doc. https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-ratelimit-headers

**Comment by GavinChenYan** [comment]
We need to add the rate limit response header based on this doc. https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-ratelimit-headers

      RateLimit-Limit: 10
      RateLimit-Remaining: 1
      RateLimit-Reset: 7

**Comment by stevehu** [comment]
This is already implemented in the rate-limit.
