### ISSUE TITLE
NullPointer exception on Mask.replaceWithMask() when parameter stringToBeMasked is null

### ISSUE THREAD

**Issue by yapkm01** [networknt/light-4j#1208]
The Mask.replaceWithMask() method will throw a NullPointer exception when parameter stringToBMasked is null. Way to produce this error is as follows as an example:

a) 2 handlers (handler-a & handler-b)
b) handler-a requires request header clientId
c) handler-b does not need this header
d) mask.yml has this field clientid
e) handler-b process a load coming in. since it does not has the above request header the above method will failed at:

private static String replaceWithMask(String stringToBeMasked, char maskingChar, String regex) {
        if (stringToBeMasked.length() == 0) { <-- NullPointer exception
            return stringToBeMasked;
        }

**Comment by miklish** [comment]
Thanks for submitting this @yapkm01!

@stevehu Given the simplicity of this one, could your team code the fix?

**Comment by miklish** [comment]
@stevehu FYI: This issue exists in both the 2.x and 1.6.x branches

**Comment by stevehu** [comment]
@miklish We can take the task but it will take some time as we are focusing on the light gateway and light-portal implementation at the moment. We do have a plan to improve the mask in the pipeline before moving the mask to the http-sidecar. If you need it urgently, you can submit a PR. I haven't looked into it but I am guessing it is an easy fix. Thanks.

**Comment by miklish** [comment]
I've found other cases where NPE's could occur... will include these in the PR

**Comment by miklish** [comment]
@stevehu Are there any cases where you would *want* an exception thrown if the input is null?

I've made changes such that all of the Mask methods return null if the input is null... however, I'm worried that may be a case of "failing silently" rather than alertng the developer to a runtime issue...

**Comment by stevehu** [comment]
@miklish I think it makes sense to return null if the input is null. What is the current behaviour if the input is null? NPE?

**Comment by miklish** [comment]
Yes. In MastkTest, maskString fails with input null + key = "uri". All overloads of maskJson fail with input = "null".
maskRegex is the only one able to handle null inputs. Will be submitting a PR today

**Comment by miklish** [comment]
@stevehu  PR has been created -- https://github.com/networknt/light-4j/pull/1222
@jsu216 @yapkm01 @stevehu -- Please review

**Comment by stevehu** [comment]
This has been released in 1.6.39. Closing the issue...
