### ISSUE TITLE
Customize return of the status from cross-cutting concerns

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#122]
1. Allow customization of the return from common modules implementing cross-cutting concderns.

Ex.: current
{
           “statusCode”: “500",
           “code”: “ERR10010",
           “message”: “RUNTIME_EXCEPTION”,
           “description”: “Unexpected runtime exception”
       }

Allow for example:
       “error”: {
           “statusCode”: “500",
           “code”: “ERR10010",
           “message”: “RUNTIME_EXCEPTION”,
           “description”: “Unexpected runtime exception”
       }

2. Allow return of list of statuses

**Comment by stevehu** [comment]
I was thinking about creating a StatusSerializer interface and users can put their implementations in service.yml to replace the default behaviour in Status class. Default will be the current one with the toString. This works for all the framework code but I don't know if it will work with APIs built on top of the framework. Also, this make Status module depends on Service which is not that bad as there is no further dependencies.
