### ISSUE TITLE
Customized client callbacks  

### ISSUE THREAD

**Issue by naveenmodi** [networknt/light-4j#133]
Please provide ability to extend HTTP2Client it in order to override the createClientCallback methods. This would help in customizing the client callbacks.

**Comment by stevehu** [comment]
@naveenmodi As per our discussion, I understand your requirement. There are multiple options and I am trying to evaluate all of them to pick up the most suitable one. Thanks.

**Comment by stevehu** [comment]
@naveenmodi The two callback functions provided in Http2Client are just reference implementations and you can already create your own callback to inject any logic you want. Here is an example of customized callback. 

https://github.com/networknt/light-4j/blob/master/client/src/main/java/com/networknt/client/oauth/OauthHelper.java
