### ISSUE TITLE
RequestTransformer not resolving rule-loader configured endpoints by prefix and method

### ISSUE THREAD

**Issue by DiogoFKT** [networknt/light-4j#1388]
Taken this configuration as an example:
_rule-loader.endpointRules: 
  /ws@post:
    request-transform:
      - ruleId: json2xml-transformer_

For POST endpoints starting with **/ws** it's not resolving to the proper config.
The ResponseTransformer DOES properly resolve and executes rules for the endpoint because it takes the endpoint formatted from Audit attachment which is attached at router handler (response is resolved _after_ egress-router)

**Comment by stevehu** [comment]
https://github.com/networknt/light-4j/pull/1389
