### ISSUE TITLE
How to handler or hook Server start finish?

### ISSUE THREAD

**Issue by HarryXQ** [networknt/light-4j#1441]
How to handler or hook Server start finish?

I have a requirement when server start finish, i need to start a work thread.

**Comment by stevehu** [comment]
implement this interface and add it to the service.yml or values.yml if the service.yml is externalized.

https://github.com/networknt/light-4j/blob/master/server/src/main/java/com/networknt/server/StartupHookProvider.java

This is how to use it.

https://github.com/networknt/kafka-sidecar/blob/master/config/local/values.yml#L28
