### ISSUE TITLE
Flaky Test In URLTest.java

### ISSUE THREAD

**Issue by tt0suzy** [networknt/light-4j#1498]
`com.networknt.registry.URLTest.testURL`

This is a flaky test, it can pass mvn test while but when run using the tool [NonDex](https://github.com/TestingResearchIllinois/NonDex), it fails. NonDex is a tool that will introduce non-determinism in certain java collections.The test shows below:

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.336 sec <<< FAILURE! - in com.networknt.registry.URLTest
testURL(com.networknt.registry.URLTest)  Time elapsed: 0.334 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...value1&key2=true&key[5=10L&key3=10&key4=3.14]&nodeType=service&ve...> but was:<...value1&key2=true&key[3=10&key4=3.14&key5=10L]&nodeType=service&ve...>
        at com.networknt.registry.URLTest.testURL(URLTest.java:102)
```
[com.networknt.registry.URLTest.txt](https://github.com/networknt/light-4j/files/10080176/com.networknt.registry.URLTest.txt)

**Steps to reproduce the failure:**
 Run the following command in light-4j:
 - First, build the module:
 `mvn install -pl registry -am -DskipTests`
- Then run the test using NonDex 
`mvn -pl registry edu.illinois:nondex-maven-plugin:2.1:nondex -Dtest=com.networknt.registry.URLTest#testURL`
- The result will be saved under the module folder in .nondex

**Comment by stevehu** [comment]
merged and closed.
