### ISSUE TITLE
Consul service discovery can block forever trying to create connection, and erases local service cache if Consul connection temporarily lost (1.6.x)

### ISSUE THREAD

**Issue by miklish** [networknt/light-4j#1503]
(for 1.6.x branch)

PR 1504 for this at https://github.com/networknt/light-4j/pull/1504

### 1. Consul service discovery can block forever trying to create a connection to Consul
- There is no timeout set during connection establishment with Consul
  - this can cause permanent connection loss to Consul, resulting in local service cache being out of sync with Consul forever
  - this can cause the Consul update thread to block forever, and can result in deadlocks in applications using light-4j for service discovery

### 2. Consul service discovery treats an empty response from Consul as a successful connection
- Consul `/v1/health/service` will always return a JSON payload
- an empty response payload should be treated as a connection error

**NOTE**: An 'empty' response means no payload at all (like `null`)... If consul returns an empty JSON list (e.g.: "`[]`"), this is NOT considered an empty response.

### 3. Consul service discovery does not preserve its local service cache during temporary loss of connection to Consul
- `ConsulClientImpl.lookupHealthService()` returns ambiguous results:
  - failed connections to Consul, and successful connections to Consul, cannot be distinguished from the data it returns, therefore...
  - users of this method cannot determine whether to preserve or update the local service cache

**Comment by stevehu** [comment]
Merged and released.
