### ISSUE TITLE
Add the ability to reset the connection in the Client Module by configurable discriminators

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#155]
For better resource consumption and load balancing, introduce the ability to reset the connection based on time or the invocation count.

Consumer applications or APIs can also handle it within their code, as an alternative.

This is an exploratory task and an enhancement to be introduced after careful consideration

**Comment by stevehu** [comment]
Light4j recommends caching client connection for reuse and periodically closing it, is there any plan to build functionality/ module(say, ConnectionCache) to handle this?
 
This is what it would do -
 
1)      ConnectionCache maintains a map of different API hosts and corresponding connection objects –
{
                “10.2.xx.xx:9001” : ClientConnectionAPI_A_9001,
“10.2.xx.xx:9002” : ClientConnectionAPI_A_9002,
“10.3.xx.xx:8402” : ClientConnectionAPI_B_8402,
“10.3.xx.xx:8403” : ClientConnectionAPI_B_8403,
“10.3.xx.xx:8404” : ClientConnectionAPI_B_8404,
………and so on
 
}
2)      Client code gets connection object for an API host(could be the one returned by cluster.serviceToUrl()) –
ClientConnection  = ConnectionCache.getConnection(“10.2.xx.xx:9002”);
 
 
3)      ConnectionCache could also do the job of periodically closing the connection after a number of requests or minutes, and assign a new connection object.

**Comment by stevehu** [comment]
This has been addressed in another issue and the configuration is in the client.yml file.
