### ISSUE TITLE
RateLimit handler does not support path prefix

### ISSUE THREAD

**Issue by DiogoFKT** [networknt/light-4j#1585]
Below configuration is not being properly applied for an example URL being hit as **HTTPS://<server>/v1/petstore/something**

limit.enabled: true
limit.key: server
server:
  /v1/petstore: 100/s 20000/d

https://github.com/networknt/light-4j/blob/62263e5b3713e8145df8b573a156d14f81a01de3/rate-limit/src/main/java/com/networknt/limit/RateLimiter.java#L226

**Comment by stevehu** [comment]
Yes. It uses the exact request path for the lookup. I will make the change to support the path prefix.

**Comment by stevehu** [comment]
This has been implemented with this PR. 
https://github.com/networknt/light-4j/pull/1586
