### ISSUE TITLE
Support dynamic port binding for Kubernetes hostNetwork

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#162]
Enable the Server module to dynamically allocate port on the same host with a given range. Also, it can get  nodeIP from Kubernetes Downward API into the container so that Server module can register itself to Consul.

**Comment by stevehu** [comment]
This is a tutorial as part of the service discover at

https://doc.networknt.com/tutorial/common/discovery/kubernetes/

**Comment by archenroot** [comment]
That is nice work, actually if I will be able to prepare the presentation we discussed on other issue here, I will fly on 14. March to Talin to present light4j as future platform for building systems for energy operators within EU. and especially Mesos and/or Kubernetes easy to use features are also in the scope as we discuss pure containerised as much as possible automated environments. 

Ladislav

**Comment by stevehu** [comment]
This is a way that we can push the performance limit on Kubernetes. Once you have thousands of services running, any proxies in between will kill your performance. Even layer 4 forwarding based on Iptables won't work. IPVS is still beta in Kubernetes 1.9 and I have high hope on it in the future. 

Another reason we have to do client side discovery is to support multiple testing environments in the same Kubernetes cluster. It resolves a lot of painful issues in monolithic applications. 

https://doc.networknt.com/design/env-segregation/
