### ISSUE TITLE
Http2Client load public cert and self-signed cert  

### ISSUE THREAD

**Issue by GavinChenYan** [networknt/light-4j#1640]
Currently Http2Client in client module load TLS cert for TLS handshake with following logic:

                    String trustStoreName = System.getProperty(TRUST_STORE_PROPERTY);
                    String trustStorePass = System.getProperty(TRUST_STORE_PASSWORD_PROPERTY);
                    if (trustStoreName != null && trustStorePass != null) {
                        if(logger.isInfoEnabled()) logger.info("Loading trust store from system property at " + Encode.forJava(trustStoreName));
                    } else {
                        trustStoreName = (String) tlsMap.get(TRUST_STORE);
                        trustStorePass = (String) tlsMap.get(TRUST_STORE_PASS);
                        if(trustStorePass == null) {
                            logger.error(new Status(CONFIG_PROPERTY_MISSING, TRUST_STORE_PASS, "client.yml").toString());
                        }
                        if(logger.isInfoEnabled()) logger.info("Loading trust store from config at " + Encode.forJava(trustStoreName));
                    }

So it will load public cert OR self-signed client trust. 

But for some case, the http client will need call some API with public CA issued cert and call some other APIs with self-signed cert.
We need add config and change logic to allow Http2Client load both public cert and client truststore together

**Comment by stevehu** [comment]
It makes perfect sense. Most of our users use the client.keystore and add public site certificates to it. It will be great if we can combine both together.
