### ISSUE TITLE
vague comment in `URLImpl.java`

### ISSUE THREAD

**Issue by jelgun** [networknt/light-4j#1721]
The comment in https://github.com/jelgun/light-4j/blob/master//registry/src/main/java/com/networknt/registry/URLImpl.java#L41 is difficult to understand. Is it possible to explain what it refers to in more detail?

**Comment by stevehu** [comment]
It is a misleading comment and can be removed. Thanks a lot for pointing it out.

**Comment by stevehu** [comment]
@jelgun I have removed the line in the master branch. Thanks.
