### ISSUE TITLE
Config class to support absolute path for config files

### ISSUE THREAD

**Issue by zabooma** [networknt/light-4j#1812]
Currently all config files are expected to be in the folder pointed by the light config settings. Hoowever this does not work well when JVM arguments are used for setting client keystore and truststore. JVM needs to be them defined as absolute path or relative to the current folder, not to the light config. This causes  loading of the keystores and truststores to fail in light-4j if JVM arguments are used.
Config loader needs to recognize if the absolute path is used and act accoordingly.

**Comment by stevehu** [comment]
I guess you want to pass the keystone or truststore paths from the command line with an absolute path. It should be supported. BTW, we also support the cacerts that come with the JDK as well with a switch in the client.yml file.

**Comment by zabooma** [comment]
Problem is that current code assumes that file which was specified in JVM argument is assumed to be relative to the light config folder, when in fact it is an absolute path. See my fix in the associated PR
