### ISSUE TITLE
Using dependency injection with annotations

### ISSUE THREAD

**Issue by rohit-zabbed** [networknt/light-4j#182]
While looking at examples, I saw some references of DI, but I couldn't get constructor injection working by default. Is there a way to do DI either spring-boot way or guice or dagger framework. 
Some reference would be nice.

**Comment by stevehu** [comment]
@rohit-zabbed We have evaluated all existing DI frameworks before building something new. Most of our customers are using Docker container to deliver their services to the cloud environment and they need to change the injections in certain environments with just configuration changes in service.yml file. With annotations, you have to change the source code and repackage the application. 

The following is a link to several tutorials on how to use the service module in light-4j. 

https://www.networknt.com/tutorial/common/service/
