### ISSUE TITLE
Allow configurable time outs for Consul calls

### ISSUE THREAD

**Issue by zabooma** [networknt/light-4j#1820]
PR: [1821](https://github.com/networknt/light-4j/pull/1821)
Update Consul calls so that non-blocking-query calls do not use the same (up to 10 minute) timeout as blocking query calls, and cleanup unused OptionMap initialization in ConsulClientImpl constructor and import.

**Comment by miklish** [comment]
@zabooma - Please update to add and use new method ConsulUtils.getNonBlockingWaitInSecond()
