### ISSUE TITLE
add a new middleware handler to push metrics to Kafka topic directly

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#194]
One of the customers is asking if we can push the metrics to a Kafka topic so that they can create microservices to stream process it before the data is landing into Big Data Store. Numeric alerts are generated based on AI algorithms in the stream processing to facilitate real-time active monitor instead of Influxdb and Prometheus.

**Comment by ankh6** [comment]
Hi @stevehu I am new to the open-source. I'd like to take this issue for my first contribution

**Comment by stevehu** [comment]
@ankh6 Welcome to the team. This is the first step for the light-4j observability integration in the light-portal. Eventually, we will push metrics, logs and open tracing to Kafka and process them together on the light-portal to give users a centralized view of their services. I will write up an article for the big picture when I have time. 

For this particular test, we just need to have another reporter implementation in the metrics module. Take a look at the module and let me know if you have any questions. Thanks.

**Comment by stevehu** [comment]
This can be done with the kafka-sidecar in a K8s environment.
