### ISSUE TITLE
Dependency in /body module seems to be in the wrong scope.

### ISSUE THREAD

**Issue by HappyHacker123** [networknt/light-4j#1948]
# Problem Description
Dependency "com.networknt:status" in the "body" module is set to the default dependency scope **"compile"**. However, it seems that it's only used in the tests with classes [com.networknt.exception.ClientException, com.networknt.status.Status].
```
        <dependency>
            <groupId>com.networknt</groupId>
            <artifactId>status</artifactId>
        </dependency>
```
# Possible Outcome
This brings redundant compile time dependency not only for light-4j, but also for projects using light-4j, resulting in enlarged dependency tree.
# Solution
To fix the problem, i change the dependency scope to test, recompile the module and run the tests. The module is successfully compiled and all tests have passed after the changes.

**Comment by HappyHacker123** [comment]
@stevehu Could you help me review this issue? Thx :p

**Comment by stevehu** [comment]
@HappyHacker123 You are right. I have merged the PR. Thanks a lot for your help.
