### ISSUE TITLE
Undeclared dependency identified in client module.

### ISSUE THREAD

**Issue by HappyHacker123** [networknt/light-4j#2001]
# Problem desciption
The module client currently relies on a transitive dependency that hasn't been explicitly declared.

It seems that a wide range of classes of xnio-api are used by client both at compile and test time.
```
[org.xnio.ChannelListeners, org.xnio.IoFuture, org.xnio.ssl.SslConnection, org.xnio.ssl.XnioSsl, org.xnio.Xnio, org.xnio.XnioWorker, org.xnio.ChannelListener, org.xnio.conduits.ConduitStreamSinkChannel, org.xnio.ChannelExceptionHandler, org.xnio.channels.StreamSourceChannel, org.xnio.conduits.ConduitStreamSourceChannel, org.xnio.XnioIoThread, org.xnio.OptionMap, org.xnio.Options, org.xnio.StreamConnection, org.xnio.FutureResult, org.xnio.channels.StreamSinkChannel, org.xnio.conduits.PushBackStreamSourceConduit, org.xnio.IoUtils]
```
It runs correctly at present due to the introduction of this dependency through transitivity.
```
com.networknt:client:2.1.29-SNAPSHOT:: -> io.undertow:undertow-core:2.3.10.Final::compile -> org.jboss.xnio:xnio-api:3.8.8.Final::compile
```

# Possible Outcome:

Relying solely on transitive dependencies makes the project susceptible to changes outside your control. Failure or instability in the project's functionality due to changes in transitive dependencies caused by alterations or removal of the introducing transitive dependency.

# Possible Solution
We should explicitly declare the dependency in our pom.xml to ensure it is clearly documented as a project dependency.

**Comment by stevehu** [comment]
We have a discussion in the PR regarding this issue and the final decision is to keep the current dependencies.
