### ISSUE TITLE
Remove unused code in SimpleUndertowConnectionMaker (1.6.x)

### ISSUE THREAD

**Issue by miklish** [networknt/light-4j#2023]
PR: https://github.com/networknt/light-4j/pull/2024

The `reuseConnection()` method in `SimpleConnectionMaker` interface (`com.networknt.client.simplepool`) was removed in PR https://github.com/networknt/light-4j/pull/1963 (SimpleConnectionPool v2), so there is no longer a need for this method in SimpleUndertowConnectionMaker.

**Comment by stevehu** [comment]
PR is merged.

**Comment by stevehu** [comment]
* Reduced API Surface: Removed the unused reuseConnection and overloaded makeConnection methods from the SimpleConnectionMaker interface and its implementations.
* Simplified Borrowing: Streamlined the SimpleConnectionHolder.borrow() logic by removing redundant flags and method calls.
* Verified Correctness: Confirmed that all SimpleURIConnectionPool tests pass and the client module builds successfully.
