### ISSUE TITLE
Ensure leaked connections are closed in SimpleURIConnectionPool.restore() (SimplePool v2) (1.6.x)

### ISSUE THREAD

**Issue by miklish** [networknt/light-4j#2028]
PR: https://github.com/networknt/light-4j/pull/2042

(related to Issue: https://github.com/networknt/light-4j/issues/2053 - was intended to be merged before https://github.com/networknt/light-4j/issues/2053 - this is why the 'Files changed' is only a change to documentation)

In SimplePool v1, a leaked-connection check (`findAndCloseLeakedConnections()` method) was done in both the `borrow()` and `restore()` methods of `SimpleURIConnectionPool`. In SimplePool v2, the leaked-connection check in `restore()` was removed. This check should be added back.

The `findAndCloseLeakedConnections()` method must also be moved to the start of `borrow()`. When at the end of the `borrow()` method, the connection leak check can be skipped due to `borrow()` exiting via an exception (which can be thrown by `SimpleConnectionMaker.makeConnection()` if connection-creation fails) before executing the leak check.

The `SimpleConnectionState.borrow()` method needs to remove the unused `connectionCreateTimeout` argument. Since this method is only used internally by `SimpleURIConnectionPool`, it is not a breaking change.

Also, some refactorings and documentation updates can be done to clarify the code. These refactorings are at the SimplePool internal implementation level, and so are not breaking changes.

Finally, to coincide with re-addition of connection leak checking in the `restore()` method, and the change in its placement in both `borrow()` and `restore()`, the connection leak checking mock test has been updated (specifically, the `MockTimeoutLeakedConnection` class has been updated) to provide more information on connection leak finding and fixing.

**Comment by stevehu** [comment]
* Optimized Leak Detection: Connection leak checks are now performed at the very start of both borrow() and restore() operations in SimpleURIConnectionPool, ensuring that any leaked resources are cleaned up immediately.
* API Cleanup: Removed the unused createConnectionTimeout parameter from SimpleConnectionMaker.reuseConnection() and SimpleConnectionHolder.borrow(), making the internal API cleaner and more consistent with the 1.6.x branch.
* Full Verification: Verified the changes by compiling the client module and running the SimpleURIConnectionPoolTest suite, which passed successfully.
