### ISSUE TITLE
-Dlight-4j-config-dir not working

### ISSUE THREAD

**Issue by helloalbin** [networknt/light-4j#2062]
My application was working fine until recently. Not sure what changed in my application. Every time I start the application it's failing with an error "Failed to start server:No ports available to bind to. Tried: -1" . I think the application is not able to read the contents of -Dlight-4j-config-dir directory. I changed the log level to debug, but nothing meaningful is printing. How can I debug this issue? Is there any log that I can enable to get some information printed?

**Comment by stevehu** [comment]
There are logs in the console to indicate where the server.yml is loaded.

**Comment by helloalbin** [comment]
For some reason, my logger is not giving any meaningful data. Please see the output from my logger.

`
10:59:36,893 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.7
10:59:36,908 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [xxxx/log.xml] at [file:/xxxx/log.xml]
10:59:36,972 |-WARN in ch.qos.logback.core.model.processor.AppenderModelHandler - Appender named [stdout] not referenced. Skipping further processing.
10:59:36,972 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [log]
10:59:36,972 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
10:59:36,975 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
10:59:36,975 |-WARN in ch.qos.logback.classic.encoder.PatternLayoutEncoder@149e0f5d - As of version 1.2.0 "immediateFlush" property should be set within the enclosing Appender.
10:59:36,975 |-WARN in ch.qos.logback.classic.encoder.PatternLayoutEncoder@149e0f5d - Please move "immediateFlush" property into the enclosing appender.
10:59:36,986 |-WARN in ch.qos.logback.classic.encoder.PatternLayoutEncoder@149e0f5d - Setting the "immediateFlush" property of the enclosing appender to true
10:59:36,989 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@454325163 - setting totalSizeCap to 60 GB
10:59:36,990 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@454325163 - Archive files will be limited to [250 MB] each.
10:59:36,991 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@454325163 - No compression will be used
10:59:36,991 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@454325163 - Will use the pattern user-%d{yyyy-MM-dd}.%i.txt for the active file
10:59:37,002 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7880cdf3 - The date pattern is 'yyyy-MM-dd' from file name pattern 'log-%d{yyyy-MM-dd}.%i.txt'.
10:59:37,002 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7880cdf3 - Roll-over at midnight.
10:59:37,005 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7880cdf3 - Setting initial period to 2024-01-14T10:54:18.881Z
10:59:37,006 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[log] - Active log file name: /temp/log.log
10:59:37,006 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[log] - File property is set to [/temp/log.log]
10:59:37,006 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [audit]
10:59:37,006 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
10:59:37,006 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
10:59:37,007 |-WARN in ch.qos.logback.classic.encoder.PatternLayoutEncoder@5be6e01c - As of version 1.2.0 "immediateFlush" property should be set within the enclosing Appender.
10:59:37,007 |-WARN in ch.qos.logback.classic.encoder.PatternLayoutEncoder@5be6e01c - Please move "immediateFlush" property into the enclosing appender.
10:59:37,007 |-WARN in ch.qos.logback.classic.encoder.PatternLayoutEncoder@5be6e01c - Setting the "immediateFlush" property of the enclosing appender to true
10:59:37,007 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@1c93084c - Will use zip compression
10:59:37,007 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[audit] - Active log file name: /temp/log_audit.log
10:59:37,007 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[audit] - File property is set to [/temp/log_audit.log]
10:59:37,008 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to ERROR
10:59:37,008 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [log] to Logger[ROOT]
10:59:37,008 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.networknt.dump] to ERROR
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.networknt.dump] to false
10:59:37,010 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [log] to Logger[com.networknt.dump]
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [io.undertow] to ERROR
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [io.undertow] to false
10:59:37,010 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [log] to Logger[io.undertow]
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.networknt] to DEBUG
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.networknt] to false
10:59:37,010 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [log] to Logger[com.networknt]
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.networknt.openapi] to ERROR
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.networknt.openapi] to false
10:59:37,010 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [log] to Logger[com.networknt.openapi]
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.zaxxer] to DEBUG
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.zaxxer] to false
10:59:37,010 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [log] to Logger[com.zaxxer]
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.networknt.audit] to ERROR
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.networknt.audit] to false
10:59:37,010 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [log] to Logger[com.networknt.audit]
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.networknt.metrics] to ERROR
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.networknt.metrics] to false
10:59:37,010 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [log] to Logger[com.networknt.metrics]
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.rpt.redparrot] to DEBUG
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.rpt.redparrot] to false
10:59:37,010 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [log] to Logger[com.rpt.redparrot]
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.networknt.server] to DEBUG
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.networknt.server] to false
10:59:37,010 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [log] to Logger[com.networknt.server]
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.networknt.config] to DEBUG
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.networknt.config] to false
10:59:37,010 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [log] to Logger[com.networknt.config]
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [Audit] to ERROR
10:59:37,010 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [Audit] to false
10:59:37,010 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [audit] to Logger[Audit]
10:59:37,010 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@6ef888f6 - End of configuration.
10:59:37,010 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@10e92f8f - Registering current configuration as safe fallback point`

Log file

`<logger name="com.networknt" level="debug" additivity="false">
		<appender-ref ref="log" />
	</logger>`

Is there anything else I need to do to get the logs printed?
