### ISSUE TITLE
JwtVerifier not reading certificates

### ISSUE THREAD

**Issue by ForwardKeys** [networknt/light-4j#2091]
Hi, we've seen that in the last version of the JwtVerifier, the certMap is actually never populated:

[JwtVerifier.java]([https://github.com/networknt/light-4j/blob/master/security/src/main/java/com/networknt/security/JwtVerifier.java](https://github.com/networknt/light-4j/issues/url))

In previous versions it was populated with the constructor.

According to _security.yml_, in case we are using light-oauth, KeyResolver _X509Certificate_ should be used, however, since JwtVerifier is not populating the map of certificates, and not even checking the String _X509Certificate_ (it's their in the code, but doing nothing), with version 2.1.31 the validation of the token done in JwtVerifier has stopped working. We've seen that apparently, the open-security.yml now must include the keyResolver (it wasn't mandatory in previous versions). Could it be that more parameters are needed in this version to have JwtWorking? We've spotted this when upgrading from 2.0.32

**Comment by stevehu** [comment]
We are moving away from using JWK instead of X509 for the signature verification. This aligns with other OAuth 2.0 providers.

**Comment by ForwardKeys** [comment]
Understood, thanks @stevehu. However, how can we make it work in its current status? We can find nothing in the documentation about what's replacing JwtVerifier

**Comment by stevehu** [comment]
You need a real OAuth 2.0 provider to make it work. Otherwise, you have to disable the security for now. I am working on an OAuth 2.0 implementation in the cloud and it should be available to developers for free.

**Comment by ForwardKeys** [comment]
Sorry, @stevehu, I don't know if I'm understanding this last part. We were using Light-Oauth. Now JwtVerifier is not working anymore, and in production environments disabling the security is not an option, as you can imagine. Does that mean that Light-Oauth is no longer valid?

**Comment by stevehu** [comment]
The light-oauth2 is a reference implementation for demo purposes. It is a placeholder for other OAuth 2.0 providers for enterprise usage. We have an enterprise implementation of oauth-kafka for enterprise users, which will soon be deployed to the cloud to offer services to small and medium businesses. Meanwhile, please stay on the light-oauth2 for a while, and we will offer the cloud service to you at a price you cannot refuse. Thanks.
