### ISSUE TITLE
Possible dependency conflict due to version conflict in /client.

### ISSUE THREAD

**Issue by HappyHacker123** [networknt/light-4j#2189]
# Problem description

Current jboss-threads is declared as version  2.3.2.Final in the parent pom's dependencyManagement block like this. 
```
<dependency>
      <groupId>org.jboss.threads</groupId>
      <artifactId>jboss-threads</artifactId>
      <version>2.3.2.Final</version>
</dependency>
```

But undertow-core in **client** module is pulling in jboss-threads with version 3.5.0.Final. Its version is overrided by 2.3.2.Final because of the declaration in the parent pom, this caused version conflict for jboss-threads and for jboss-logging as can be seen from the dependency tree below. This may cause dependency conflict and induce runtime exception.

```
[INFO] +- io.undertow:undertow-core:jar:2.3.7.Final:compile
...
[INFO] |  \- org.jboss.threads:jboss-threads:jar:2.3.2.Final:compile (version managed from 3.5.0.Final)
[INFO] |     \- (org.jboss.logging:jboss-logging:jar:3.3.1.Final:compile - omitted for conflict with 3.4.3.Final)
```

# Possible solution 

As far as i can see, light-4j is not using jboss-threads itself. If the declaration in dependencyManagement block is not on purpose, it's better to remove it and leave the version as it is. I try to remove the declaration and the tests pass as before.

**Comment by HappyHacker123** [comment]
Could you please take a look at this issue @stevehu ? many thanks :)

**Comment by stevehu** [comment]
@HappyHacker123 The current light-4j is using 2.3.12.Final now. Would you like to upgrade this library to the same version? By the way, the undertow core is for testing only and it is not a dependency for the production.

**Comment by HappyHacker123** [comment]
Yes, I think it's better to align the versions to avoid dependency conflict, do you think it's acceptable :)? BTW, i found no declaration of jboss-threads as a dependency in light-4j. I would appreciate it if you could kindly point it out.

> the undertow core is for testing only and it is not a dependency for the production

Thanks for reminding! But it seems that undertow-core has scope compile rather than test?

**Comment by stevehu** [comment]
I just double-checked light-4j again and the current undertow version is 2.3.12.Final, which is the latest version. Could you please point out where the 2.3.2.Final is introduced?

**Comment by HappyHacker123** [comment]
> I just double-checked light-4j again and the current undertow version is 2.3.12.Final, which is the latest version. Could you please point out where the 2.3.2.Final is introduced?

Thanks for your patience :).  I'm referring to the **client** module i.e. **client/pom.xml**. The dependency tree i provided earlier is indeed not up-to-date with the latest version. I run "**mvn -pl client dependency:tree -Dverbose**" again and  here's the updated version.
```
[INFO] +- io.undertow:undertow-core:jar:2.3.10.Final:compile
...
[INFO] |  \- org.jboss.threads:jboss-threads:jar:2.3.2.Final:compile (version managed from 3.5.0.Final)
[INFO] |     \- (org.jboss.logging:jboss-logging:jar:3.3.1.Final:compile - omitted for conflict with 3.4.3.Final)
```
And the place that declare the version  of **jboss-threads**  is the pom.xml under the root directory.

```
    <dependencyManagement>
            ...
            <dependency>
                <groupId>org.jboss.threads</groupId>
                <artifactId>jboss-threads</artifactId>
                <version>2.3.2.Final</version>
            </dependency>
           ...
    </dependencyManagement>
```
As you can see, the problem still exists. The **2.3.2.Final** is the final version of **jboss-threads** after conflict, but not the version of **undertow-core**.  The role that undertow-core plays is only pulling in jboss-threads, so it's the version of **jboss-threads** that matters. Its original version is **3.5.0.final** as can be seen from the dependency tree, but is downgraded to  **2.3.2.Final** due to the version declared in parent pom.

**Comment by stevehu** [comment]
@HappyHacker123 I found the issue with your help and here is the PR to get the issue resolved. Thanks a lot for your help. 

https://github.com/networknt/light-4j/pull/2195

**Comment by HappyHacker123** [comment]
@stevehu Thanks for your patience!
