### ISSUE TITLE
Router rewriteMethod property does not work with path prefix

### ISSUE THREAD

**Issue by DiogoFKT** [networknt/light-4j#2231]
`router.methodRewriteRules` property only works with full path because StringUtils must match string.split("/") item count between full path against configured path prefix

https://github.com/networknt/light-4j/blob/master/utility/src/main/java/com/networknt/utility/StringUtils.java#L1499-L1503

Called here:

https://github.com/networknt/light-4j/blob/2.1.33/proxy-handler/src/main/java/com/networknt/handler/ProxyHandler.java#L627

We need the property to allow only path prefix so to apply to any endpoint that matches the path prefix

**Comment by stevehu** [comment]
@DiogoFKT We have the same issue for timeout overwritten as well and it is fixed at the same time. Thanks a lot for pointing it out.
