### ISSUE TITLE
light-4j 1.6.x : Updating dependencies in light-4j with CVEs to: jose4j 0.9.6

### ISSUE THREAD

**Issue by mihai-vladuc** [networknt/light-4j#2264]
Story : https://jira.cibcatl.com/browse/API-617

jose4j  dependency in pom.xml to be upgrade from jose4j:0.9.4 to jose4:j0.9.6

**Comment by mihai-vladuc** [comment]
to be reopen after we shall do the testing

**Comment by stevehu** [comment]
I have updated all repos for 1.6.x branch with light-bot. https://github.com/networknt/light-config-test/issues/819
