### ISSUE TITLE
Should DecryptUtil be moved to the utility package?

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-4j#231]
https://github.com/networknt/light-4j/blob/master/common/src/main/java/com/networknt/common/DecryptUtil.java

And/Or should we consider consolidating common and utility under the same sub package?

**Comment by stevehu** [comment]
I was in the utility package before. The reason that I have created a separate module is to share something between client and server.

**Comment by stevehu** [comment]
I am also thinking to remove those header constants out of utility module to make it not depending on the Undertow. What do you think?

**Comment by NicholasAzar** [comment]
For the dependency i dont think it makes much difference.. anyone using the framework will already be bringing it in so i dont think it would add much to remove it from `utility`.

Although it does seem like the `utility` module is being used as a `common`, while `common` if anything is a `shared`. Realistically i don't yet see the benefit to have the `shared` module.. why not have client and server both depend on `common`?
