### ISSUE TITLE
UnifiedSecurity handler fails with 500 when Authorization header only contains Bearer

### ISSUE THREAD

**Issue by DiogoFKT** [networknt/light-4j#2365]
We need to wrap the substring function with try/catch and return 401 when fails

https://github.com/networknt/light-4j/blob/57cf110dcca362465868c0e3c1d0c3b10556c9fa/unified-security/src/main/java/com/networknt/security/UnifiedSecurityHandler.java#L137C33-L137C75

**Comment by stevehu** [comment]
https://github.com/networknt/light-4j/commit/0fd856e0481e60762fe11cf804eb0197d7a26444

**Comment by DiogoFKT** [comment]
Great! Thanks!
