### ISSUE TITLE
Client module logging integration functionality

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-4j#237]
Currently all services built on with l4j could have metrics logging into an influxdb instance, however is there any equivalent functionality on the roadmap for client requests? Ie. would there be any statistics for the number of failed requests that a client using the client module made to a particular service?

**Comment by stevehu** [comment]
This has been asked by somebody before and it is implemented in the Http2Client as a full callback function. The response time is calculated and returned in the callback. The value can be logged by the client application. However, it shouldn't be populated to the InfluxDB as only service metrics will be submitted there. In fact, the client response time is almost the same as the service response time captured in the metrics. The only difference would be the network latency. 

https://github.com/networknt/light-4j/blob/master/client/src/main/java/com/networknt/client/Http2Client.java#L622

**Comment by NicholasAzar** [comment]
Thanks @stevehu !
