### ISSUE TITLE
networknt page is not working

### ISSUE THREAD

**Issue by thilux** [networknt/light-4j#238]
Hello,

I am trying to check the tutorials and examples for light4j, however it seems that the page they were being hosted is no longer available:

![image](https://user-images.githubusercontent.com/4541251/42381640-15f038f8-8108-11e8-979d-288665e30228.png)

Should the links be updated to somewhere else?

Thank you!
TS

**Comment by gonzalovazquez** [comment]
Hi,

We have our documentation hosted here:

https://doc.networknt.com/

Cheers,
Gonzalo

**Comment by thilux** [comment]
Thank you @gonzalovazquez !

The README should be updated. There are some links pointing to https://networknet.github.io.

Thank you!

**Comment by stevehu** [comment]
@thilux Thanks a lot for bringing it up. I have fixed the links in the README.md 

https://github.com/networknt/light-4j/issues/239

**Comment by thilux** [comment]
Great! I think that closes the matter then.

Thank you!

**Comment by stevehu** [comment]
The master branch is not updated as of yet and it will be updated in the next release. Thanks.

**Comment by stevehu** [comment]
This should be fixed after the 1.5.17 release.
