### ISSUE TITLE
Add circuit breaker to the client module

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#241]
Previously, we recommend using Hystrix for high volume service invocation. However, most of the times, it is overkill. It makes sense that we implement the pattern in the client module.

**Comment by NicholasAzar** [comment]
@stevehu do we already have the interfaces we want to provide for this? or do we still need some solution discussions?

**Comment by stevehu** [comment]
related to this issue. https://github.com/networknt/light-4j/issues/242

**Comment by stevehu** [comment]
related to this issue https://github.com/networknt/light-4j/issues/155

**Comment by stevehu** [comment]
related to this issue https://github.com/networknt/light-4j/issues/240

**Comment by jefperito** [comment]
we have a brand new (scaffold) circuit breaker: https://github.com/networknt/light-4j/blob/28640759e1881f897bfcaadd14a70d159e2aa556/client/src/main/java/com/networknt/client/circuitbreaker/CircuitBreaker.java

what do you think guys?

**Comment by stevehu** [comment]
@jefperito I have reviewed the implementation and it looks very nice.

**Comment by ddobrin** [comment]
Looks good to me
