### ISSUE TITLE
catastrophic setExchangeStatus calls without args

### ISSUE THREAD

**Issue by logi** [networknt/light-4j#244]
If `LightHttpHandler.setExchaggeStatus` is called without enough `args` to populate the description template string for the particular state's description, then this raises an exception which eclipses the original problem. This tends to happen when the user (me) is doing something wrong and hitting unexpected and less tested code paths. The user (me) is also already sufficiently confused without the error handler failing.

One example:
```
java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2519)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at com.networknt.status.Status.<init>(Status.java:89)
        at com.networknt.handler.LightHttpHandler.setExchangeStatus(LightHttpHandler.java:21)
        at com.networknt.handler.OrchestrationHandler.handleRequest(OrchestrationHandler.java:15)
```

I have a local change to `Status` that I can submit as a PR which logs an informative warning and then sets the intended status but leaves the `%s` (or other format specifiers) in the description.

**Comment by stevehu** [comment]
@ddobrin Could you please take a look at the PR and confirm if it also resolves the issue you are facing in case the handler is not defined correctly?

**Comment by ddobrin** [comment]
I will look at this issue within the next 48h

**Comment by ddobrin** [comment]
While this change is fine, it does not address the issue I was failing.
As I have to split and refactor some code and repos, I will reproduce the issue exactly and post the steps here, within this week

**Comment by ddobrin** [comment]
Reproduced and opened a new issue #247.

Fixes will be introduced while addressing that respective issue.

This fix does not address those issues

**Comment by stevehu** [comment]
@ddobrin Thanks for the confirmation. This issue has been resolved and I am closing it.
