### ISSUE TITLE
Support for multiple server URLs in OpenAPI

### ISSUE THREAD

**Issue by siom79** [networknt/light-4j#248]
I want to implement a second version of my API. Therefore I have generated the code for version 2 using light-4j-codegen with the modified version of my OpenAPI specification into a package that contains ``v2``:
```
java -jar codegen-cli.jar -c config_v2.json -f openapi -o api-openapi -m openapi_v2.json
```
The ``PathHandlerProvider`` gets overridden by the light-4j-codegen tool, so I had to adjust it:
```
public class PathHandlerProvider implements HandlerProvider {
    @Override
    public HttpHandler getHandler() {
        return Handlers.routing()
        
            .add(Methods.GET, "/v1/health", new HealthGetHandler())
            .add(Methods.GET, "/v1/server/info", new ServerInfoGetHandler())
            .add(Methods.PUT, "/v1/persons", new com.example.api.v1.handler.PersonsPutHandler())
            .add(Methods.GET, "/v1/persons/{personId}", new com.example.api.v1.handler.PersonsPersonIdGetHandler())
        
            .add(Methods.GET, "/v2/health", new HealthGetHandler())
            .add(Methods.GET, "/v2/server/info", new ServerInfoGetHandler())
            .add(Methods.PUT, "/v2/persons", new com.example.api.v2.handler.PersonsPutHandler())
            .add(Methods.GET, "/v2/persons/{personId}", new com.example.api.v2.handler.PersonsPersonIdGetHandler())
        ;
    }
}
```
The OpenAPI specification contains the following servers section:
```
"servers": [
    {
		"url": "http://localhost/v2"
	},
	{
		"url": "http://localhost/v1"
	}
],
```
When I request the URL ``http://localhost:8080/v1/persons/23`` this results in the following error message:
```
{
    "statusCode": 404,
    "code": "ERR10007",
    "message": "INVALID_REQUEST_PATH",
    "description": "Request path /iprs/v1/persons/23 cannot be found in the spec.",
    "severity": "ERROR"
}
```
A request to ``http://localhost:8080/v2/persons/23`` is successful.

When I change the servers section such that the URL with ``v1`` is the first one, the URL can be requested successfully, but the request to ``v2`` fails.

I guess that the ``OpenApiHandler`` does only evaluate the first ``url`` in the servers section when processing an incoming request.

Would it be possible to support both URLs?

**Comment by PeterKieu** [comment]
@siom79 I suggest that you should you a simple way:  Use version in Api endpoint paths, not in server paths.
**(1) in openapi.yaml** (similar to convert to Json format)
servers:    
  - url: https://{environment}
    variables:
      environment:
        default: localhost:8443    # Dev 
        enum:
          - apimobile.yourcompany.com         # Production server
          - staging-apimobile.yourcompany.com # Staging server
          - localhost:8443             # Dev  
paths:
  /v1/persons/{personId}:
  /v2/persons/{personId}:

**(2) Coding the handler:** 
public class PathHandlerProvider implements HandlerProvider {
    @Override
    public HttpHandler getHandler() {
        return Handlers.routing()

            .add(Methods.GET, "/v1/persons/{personId}", new com.example.api.v1.handler.PersonsPersonIdGetHandler())

            .add(Methods.GET, "/v2/persons/{personId}", new com.example.api.v2.handler.PersonsPersonIdGetHandler())
        ;
    }
}

**Comment by siom79** [comment]
Yes, we can use such workaround. But it has the drawback that you have to
specify two models in your OpenAPI file in case the model changes between
the versions.
It would be much better to have two separate files that you can develop and
diff independently.

PeterKieu <notifications@github.com> schrieb am Fr., 22. Feb. 2019, 22:25:

**Comment by stevehu** [comment]
@siom79 Since this issue was opened, a lot of features have been added to the platform. One of the features is the handler.yml which supports multiple frameworks in the same service instance. I know one company has built services to support both REST and GraphQL in the same instance. In theory, we can support two REST specifications in the same instance, the only roadblock is that we are using hard-coded  openapi.yaml as specification name now. I am wondering if you are interested in exploring it a little bit further. Thanks.

**Comment by stevehu** [comment]
The latest version supports multiple OpenAPI specifications simultaneously on the light-gateway.
