### ISSUE TITLE
health endpoint with serviceId as path parameter

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#262]
In the current stability test on Kubernetes and Consul clusters, we are using TCP health check from Consul server to registered service IP address and port number. It has a flaw as described below. 
1. A service registers itself to the consul and asks consul to ping the IP and port. 
2. When the service is crashed without a chance to deregister itself.
3. Kubernetes started another service on the same IP and reused the port number as it is dynamically allocated. 
4. Consul pings the service and it is still alive but it is not the registered service anymore. 

We can ask each service to pre-allocate a range of port numbers but it would be very hard to manage or enforce even in the same Kubernetes namespace or Openshift project. 

It looks like we cannot use TCP health check in our case although it is the most efficient one. 

The TTL based health check is also not ideal as we put a lot of load to the consul servers to update the pass and fail status by calling consul APIs. 

The only thing that is left is the HTTP health check and we need to make some changes to uniquely identify the service. I am thinking to update the /health to /health/{serviceId} in the new handler.yml so that Consul won't get status code 200 if the target service is not the same service as registered. What do you think? Thanks

**Comment by NicholasAzar** [comment]
Sounds to me that /health/{serviceId} is the best option.

**Comment by NicholasAzar** [comment]
@stevehu just to be clear on this, we're saying that the health check will implement a check to ensure that the path variable passed in matches its service id right?
Or did you mean that {serviceId} will be a hard coded path in each service for their service id?

**Comment by stevehu** [comment]
It would be a hard-coded path in the handler.yml; however, this will be generated from light-codegen so it should be transparent to the developers. 

Here is an example of the handler.yml 

https://github.com/networknt/light-example-4j/blob/develop/discovery/api_d/http-health/src/main/resources/config/handler.yml

**Comment by NicholasAzar** [comment]
So now every time they bump up the service id version in their applications they have to make sure they change both..

**Comment by stevehu** [comment]
In most of the cases, this serviceId won't be changed at all. If it is changed, then this is an extra place that needs to update. If the API is following the evolution guidelines, then there is no need to change the serviceId. Changing serviceId will impact all clients and I think it is an even bigger issue. 

https://doc.networknt.com/design/evolution/

**Comment by NicholasAzar** [comment]
@stevehu i thought that every time there's a new version of an api the service id will change.. since the version is within the service id. Is that not the case?

What was the downside of including that check within the health handler?

**Comment by stevehu** [comment]
We can put the serviceId into the header and check that in the health check handler; however, if someone wants to use a customized handler to cascade checking database, then he/she must do the same check for the serviceId. This can be easily forgotten and cause problem consul health check.
