### ISSUE TITLE
Environment config in client only applications

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-4j#272]
Currently the environment tag for registering on consul is located in the `server.yml` config. However for clients only using the light-consumer-4j module and require the change in environments as their applications get promoted, currently everyone will have to implement their own config files for the environment.

If we were to include an environment field in client.yml, we would tie every call made from the client module to that environment.. is that ok? Could there be real world cases where the same application would consume services located in different environments? 
If so, what would be the best way to handle these scenarios? Do we have a map for config based on service-name that will do the lookup when the clients initiates the request to specific services? Or is that unnecessary?

**Comment by stevehu** [comment]
You are right that the current implementation for the environment tag is working with the server.yml only for service to service communication. If you have an original client application, normally you can define the tag in any config file and client.yml is one of the candidates. However, I don't think client.yml is the right place as it will confuse the server to server communication. For the original, I would say it is an application and there should be an app.yml that can define the environment tag. What do you think?

**Comment by NicholasAzar** [comment]
@stevehu consumer.yml to be included in light-consumer-4j?

**Comment by stevehu** [comment]
I think that is a good idea.

**Comment by NicholasAzar** [comment]
Thanks! working on it..

**Comment by stevehu** [comment]
The implementation has been moved to light-consumer-4j. Close this issue.
