### ISSUE TITLE
need a way to serialize json map object to String for logging with mask

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#280]
In most of the handlers, we are dealing with Map object for the input JSON. For logging purpose, we need to serialize it into a string and mask the sensitive data like password etc. I don't want to use Jackson writeValueAsString for two reasons. 

1. We need to handle the exception
2. There is no way we can mask sensitive values. 

Create two static methods in Mask? One deals with a list and another deals with a map.

**Comment by stevehu** [comment]
I agree. That is why I was thinking to extend Mask module and utilize its config file.

**Comment by NicholasAzar** [comment]
@BalloonWen is this done?

**Comment by BalloonWen** [comment]
@NicholasAzar This was done and tested at that time but after the change of JsonPathStartupHookProvider, it may have some affection. I haven't tested after that.

**Comment by NicholasAzar** [comment]
Ok thanks, i'm thinking we should track any impact from other changes in a new issue.
