### ISSUE TITLE
BodyHandler Middleware to support configurable Content-Type

### ISSUE THREAD

**Issue by bkuberek** [networknt/light-4j#285]
Currently, `BodyHandler` middleware only supports JSON. The problem with this is that when reading the body of the request we always get a `List` or `Object` but often we have our own Interface we want to deserialize the payload into.

Ideally we can tell `BodyHandler` how to deserialize the payload into the interface we want. Perhaps we can use the `BodyHandler` configuration to to define a map where the key is the content-type and the value is the class or interface.

We should update the line below, replacing `new TypeReference<HashMap<String, Object>>() {}` with the configured interface for the content-type.

```java
body = Config.getInstance().getMapper().readValue(s, new TypeReference<HashMap<String, Object>>() {})
```

This is how I've seen it handled and I don't think we should be doing it this way:

```java
Map s = (Map)exchange.getAttachment(BodyHandler.REQUEST_BODY);
String json = objectMapper.writeValueAsString(s);
Task task = objectMapper.readValue(json, Task.class);
```

With that in mind, it would also be good if the ObjectMapper was a globally available object that can be configured during startup. This way, all calls to objectMapper reader and writer use the same configuration.

**Comment by stevehu** [comment]
@bkuberek There is an API in Jackson that converts map or list to your object and it is very efficient as the most time-consuming job to parse the String to JSON has been done by the body parser. 

onfigService configService = Config.getInstance().getMapper().convertValue(input, ConfigService.class);

Also, I am open to making the BodyParser configurable if it is backward compatible. Thanks.

**Comment by bkuberek** [comment]
That's great! Thanks for the example. Perhaps there's no need to change BodyHandler then. We can wait until there is a stronger need.
