### ISSUE TITLE
Update OAuthHelper to include new method to support SAML grant type flow

### ISSUE THREAD

**Issue by miklish** [networknt/light-4j#290]
Support must be added to support the new SAML grant type OAuth flow.

A getTokenSAMLFlow() method will be added to OAuthHelper to aid with this.

Light Router must accept a JWT and a SAML token in it's header under the header keys `assertion` (for SAML) and `client_assertion` (for JWT).

It must then `POST` these tokens* to an OAuth authorization server (encoded as `x-www-for-urlencoded`) and receive a JWT in response, and then set this new `Bearer {JWT}` in its header under the `Authorization` key before service lookup and forwarding the request. 

* - In addition to the tow tokens, the authorization server expects the following additional values in x-www-form-urlencoded payload:

- `grant_type: urn:ietf:params:oauth:grant-type:saml2-bearer`
- `scope: {blank separated list of OAuth scopes}`*
- `client_assertion_type: urn:ietf:params:oauth:client-assertion-type:jwt-bearer`

`*` Note that the scope key/value pair is optional.

**Comment by miklish** [comment]
This is currently being worked on by dguncb. I don't have access to assign issues though, and dguncb doesn't have access to be assigned. Can you set us up Steve? Thanks

**Comment by stevehu** [comment]
@miklish @dguncb I have added you the the member list. Please accept the invitation and you should have the access. Thanks.

**Comment by stevehu** [comment]
Is there a middleware handler who is responsible for intercepting the headers and calling the OAuth 2.0 provider to exchange the token?

**Comment by miklish** [comment]
Thanks Steve. We’ll need access to networknt/light-router as well (it’s where we will add the SAML grant flow handler)

Cheers,

-mike

**Comment by miklish** [comment]
We plan to add that (the new handler responsible to intercept the header and exchange tokens with auth server) to the light-router repository. I created a separate issue for that.

**Comment by stevehu** [comment]
This has been resolved by the PR https://github.com/networknt/light-4j/pull/292
