### ISSUE TITLE
Enhance logging in the AuditHandler

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#295]
Add ability to log, via configuration:
- log the information as info or error 
- log the information based on whether this is a successful response (200) or not
- log the payload, if API developers consider it useful for their environment

This issue is created based on a request from a client building on the light-4j framework

**Comment by NicholasAzar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enhance logging in the AuditHandler](https://trello.com/c/KvjzWMle/3-enhance-logging-in-the-audithandler)
