### ISSUE TITLE
Add a signed token module for information exchange

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#296]
JWT is used not only for security, but also for tamper-proof information exchange:
- **Authorization**
- **Information Exchange**: JSON Web Tokens are a good way of securely transmitting information between parties. Because JWTs can be signed—for example, using public/private key pairs—you can be sure the senders are who they say they are. Additionally, as the signature is calculated using the header and the payload, you can also verify that the content hasn't been tampered with.
(https://jwt.io/introduction/)

This module, to be called **signed-token** will allow a consumer to pass a payload with an arbitrary number of values, in the JWT body, and have its signature validated.

The module should support:
- single/multiple tokens passed in configurable locations in the request header
- validation of the signature
- extraction of the claims
- making them available in an attachment in the API flow.

Issue https://github.com/networknt/light-oauth2/issues/136 in light-oauth2 addresses the build of a token signing endpoint which can be used for signing such token

**Comment by stevehu** [comment]
This has been done with https://github.com/networknt/light-4j/pull/446
