### ISSUE TITLE
make bufferSize configurable for default buffer pool in Http2Client

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#299]
The current default value is 24*1024 which is big enough for most of the applications. However, for certain apps with big request body, we need to increase it so that it can hold the entire request. The drawback is that more memory will be used especially you have one big request with other small requests. One option is to split the service into two so that they can have their buffer size setup closer to the request size. 

In the client.yml we have added the following in the beginning. 

```
# Buffer Size in the buffer pool in KB. If should be bigger than your request or response body size.
bufferSize: 80
```
If this config variable is missing, then default 24 will be used. 

We also consolidate the BUFFER_POOL and make the POOL and SSL_BUFFER_POOL deprecated. Now they are just alias of BUFFER_POOL and will be removed in 2.x release.

**Comment by stevehu** [comment]
https://github.com/networknt/light-router/issues/22

**Comment by NicholasAzar** [comment]
Shouldn't this be changed in all repo's that reference Http2Client.POOL?
I.e. documentation, examples, test cases, etc..

**Comment by stevehu** [comment]
Yes. I will create a light-bot regex-replace to update every repo in networknt and lightapi. There are 100s projects in light-example-4j and I cannot update them manually.
