### ISSUE TITLE
Intermittent issues with Consul API discovery

### ISSUE THREAD

**Issue by kumasath** [networknt/light-4j#301]
We observed few things about the way consul discovery behaves - 

We are using version 1.5.18 of consul client. Here are the details - 
                
1)	We observed that in the class  ConsulClientImpl under method lookupHealthService() – there is a wait time specified as 10 minutes and a health check-up request waits at consul server for 10 minutes, this happens a few times and we get the response back after 10 minutes. 

String path = "/v1/health/service/" + serviceName + "?passing&wait=600s&index=" + lastConsulIndex;

If we reduce the wait time to, say 5 seconds (wait=5s), we get response from consul in 5 seconds(again intermittent)

https://github.com/networknt/light-4j/blob/1.5.18/consul/src/main/java/com/networknt/consul/client/ConsulClientImpl.java

2)	Few times we get the response back immediately irrespective of the wait time specified in the URL.

Could you shed some light on our findings? Also, we have few questions around the implementation –

1)	What is the purpose of having wait interval of 10 minutes, and subsequently holding a request for 10 minutes(in some cases). We observed we also have  lookupInterval specified at consul client end.
2)	Which parameter controls the wait at consul server, based on which the server responds immediately or after the wait timeout?

**Comment by stevehu** [comment]
@kumasath you have asked a very interesting question and it put you into the light-4j super user group :)

I have added a section in the https://doc.networknt.com/concern/consul/ but not published yet.

### Consul Blocking Queries

For service discovery, we are using Consul Blocking Queries (Long polling). It basically sends a request to the Consul server and tells Consul don't do anything within 10 minutes if the subscribed service instances are not changed. If the subscribed service instances are changed, it will return the result immediately with the changes. After 10 minutes, the request will timeout and a new request will be issued. In this way, we can maintain a list of healthy service instances all the time at the client side. If it is necessary to create a new connection, there is no need to go to Consul for a discovery as the local cache is the latest. This design is the fast way to let the client be notified if any service instance is gracefully shutdown or crashed.

**Comment by stevehu** [comment]
These two issues are for the same problem. 
https://github.com/networknt/light-4j/issues/303
