### ISSUE TITLE
JDK 11 Upgrade

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-4j#307]

**Comment by ddobrin** [comment]
I would suggest that we discuss a long-term stable branch for Java 8, as a 1.x.x and creating a 2.x.x.
A Git branching model document has previously been shared with @stevehu @chenyan71 @NicholasAzar and @miklish

**Comment by lanphan** [comment]
Do we have specific time frame to release version 2.x, @stevehu @ddobrin ?

**Comment by stevehu** [comment]
We have released [2.0.0-BETA2](https://github.com/networknt/light-4j/releases/tag/2.0.0-BETA2) weeks ago and the feedbacks are positive. I am thinking to create another config for light-bot to get the entire platform to JDK 11. I am still struggling on if we should use 2.0.x as the master branch. Some of our customers are waiting for Redhat JDK 11 docker image to be ready and we don't know when this will happen.

**Comment by ddobrin** [comment]
I know that there will be deployments in parallel with both 1.y.z and also 2.y.z.

My current client will build new APIs with 2.x, when released, however migrate from 1.x only at the time of upgrade of a microservice.

It'll be gradual and a Java 8 version will be running for the next 6-12m at a minimum
