### ISSUE TITLE
Read configurations from arbitrary directories

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#309]
The Config class offers very convenient methods to load config files in yml or json formats.

The are predicated on being available in the "light-4j-config-dir", which is specified at startup as usually with a "-D".

The Config.loadMapConfig(String fileName) could be overloaded with a directory location as:
Config.loadMapConfig(String fileName, String directoryName).

It would be useful for : 
- tools as the networknt:light-bot project for loading config files from multiple locations
- specifying configurations in multiple folders, in addition to the standard /src/main/resources/config

**Comment by NicholasAzar** [comment]
@ddobrin @stevehu Is there an rfc for this?

**Comment by ddobrin** [comment]
https://github.com/networknt/light-rfcs/pull/11

**Comment by ddobrin** [comment]
RFC has been split into 3 smaller RFCs, by problem area.
It can be found here:
https://github.com/networknt/light-rfcs/pull/15

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Read configurations from arbitrary directories](https://trello.com/c/5J1gLc4Z/82-read-configurations-from-arbitrary-directories)
