### ISSUE TITLE
Need to encrypt secrets in config files so that they won't be leaked

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#31]
One of my clients has to deployed service on data centre due to private cloud availability. Without Kubernetes to manage the secrets, we need to find a way to encrypt the secrets(password, client_secret, private key etc) in config files the first time they are loaded.

**Comment by stevehu** [comment]
After thinking about it for a while, I am convinced that secret encryption the first time server start is not that important on Linux but on Windows. Linux has more controls on who can read a file and the issue is not as critical as Windows. This is a nice to have feature but I don't think it should be high priority.

**Comment by AmaranthLIS** [comment]
[Vault](https://www.vaultproject.io/) from Hashicorp can help in this cause.

**Comment by stevehu** [comment]
Yes. Vault is the one I am looking at; however, this client has something on production in June and they cannot use docker/kubernetes/vault etc. It is a locked down data centre running Solaris. This is why we need to find a interim solution before they can move all the services to cloud. Thanks.

**Comment by stevehu** [comment]
The current solution is to separate server and client secrets into a secret.yml and it will be managed by Kubernetes Secret. The separation make it easier to move to Vault if that is required. Close the current issue for now.
