### ISSUE TITLE
Need to allow server to be embedded

### ISSUE THREAD

**Issue by farrukhnajmi** [networknt/light-4j#312]
I need to run the actual server from a system test program. Ideally the com.networknt.server.Server would allows doing this by moving the main methods content into an init() method that could be called from my test. I have created a trivial pull request https://github.com/networknt/light-4j/pull/311 that addresses this need.

**Comment by stevehu** [comment]
@farrukhnajmi I have reviewed your PR and there is no issue. I am a little curious about your use case. Could you please explain what is your test harness and why you don't want to use the built-in TestServer for your unit and integration test. This might help us to learn new testing approach. Thanks.

**Comment by stevehu** [comment]
Cool. I remember other people asked to run a light-4j instance in another Java process before and I think this resolves that issue. Thanks a lot. I have assigned the PR for other team members to review. It should be in the next release.

**Comment by farrukhnajmi** [comment]
> @farrukhnajmi I have reviewed your PR and there is no issue. I am a little curious about your use case. Could you please explain what is your test harness and why you don't want to use the built-in TestServer for your unit and integration test. This might help us to learn new testing approach. Thanks.

I am writing a system test using Spock framework. The test sends a message to a remote service and then uses an actual light-4j server (not test server) to listen for events from the remote service. This protocol is fixed and I cannot change that. My test is an end-to-end system test with no mocks. When events are received from remote service, the test compares them to expected events.

**Comment by stevehu** [comment]
This has been released in 1.5.22. Close the issue. Thank you.
