### ISSUE TITLE
light-4j benchmark

### ISSUE THREAD

**Issue by Dmole** [networknt/light-4j#315]
light-4j benchmark scores seem to have fallen
https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=plaintext
vs
https://www.techempower.com/benchmarks/#section=data-r15&hw=ph&test=plaintext
time for some fixing?
https://github.com/TechEmpower/FrameworkBenchmarks/issues?utf8=%E2%9C%93&q=light-4j

**Comment by stevehu** [comment]
@Dmole If you look at the source code there, you will realize nothing changed but the performance numbers are down significantly. I think they have changed the environment. In my opinion, these benchmarks are not close to real business scenarios. Our strength is https/2 with client-side service discovery. We really need to have a service to service benchmark comparing gateway, sidecars, and light-4j.

**Comment by Dmole** [comment]
I checked and there was a 600% drop with no environment change. There are plenty of other http/2 frameworks on that list.
My best guess at the moment is that the java change when they moved to docker is the cause.... but it's just a guess.

https://github.com/TechEmpower/FrameworkBenchmarks/issues/4218

**Comment by stevehu** [comment]
@Dmole Thanks for bringing it up to the attention of TechEmpower team. I think it is a configuration issue and we just need to compare how Undertow is configured in round 16 and later. The performance should be the same.

**Comment by stevehu** [comment]
@Dmole After the conversation we had on this topic, I have updated the test cases to upgrade to JDK11 with JDK 11 docker image. Now it is OK in the snapshot. Thanks a lot for bringing it up. 

https://www.techempower.com/benchmarks/#section=test&runid=58042695-831a-4a35-8c60-2b872a06f799&hw=ph&test=json
