### ISSUE TITLE
gzip and deflate encoding and decoding support in middleware handlers

### ISSUE THREAD

**Issue by acmeguy** [networknt/light-4j#323]
Expected behavior:
  - Requests with gzip as content-encoding should be decoded before the are processed by any request handler.

Current behavior:
   - Request body is gzipped in the handler and can not be handled properly 

Proposed steps to fix this:
  - Add gzip decoding middleware to handle this transparently

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Encode and decode middleware handlers](https://trello.com/c/GeJFM5vn/20-encode-and-decode-middleware-handlers)
