### ISSUE TITLE
Attachment Handler

### ISSUE THREAD

**Issue by thirtysixmm** [networknt/light-4j#326]
A middle ware handler to parse the form-data based on the header and put the content into an attachment. It is an optional handler that you can wire into your handler chain for a specific endpoint.

**Comment by NicholasAzar** [comment]
Will take a look

**Comment by NicholasAzar** [comment]
This is being addressed in: https://github.com/networknt/light-4j/pull/329

**Comment by stevehu** [comment]
@thirtysixmm It is scheduled to be released this weekend. 

https://trello.com/b/189msq9S/release-schedule
