### ISSUE TITLE
codegen-cli generated code does not compile - openapi-3

### ISSUE THREAD

**Issue by ashunam** [networknt/light-4j#330]
My spec:
`https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml`

My command:
` java -jar ../../tools/light4j/light-codegen/codegen-cli/target/codegen-cli.jar -f openapi -o ./ -m openapi_specs/spec.yaml  -c code_gen_config.json`

```
My config:
{
  "rootPackage": "com.home.test",
  "handlerPackage":"com.home.test",
  "modelPackage":"com.home.test",
  "artifactId": "test",
  "groupId": "com.home",
  "name": "testservice",
  "version": "1.0.0",
  "overwriteHandler": true,
  "overwriteHandlerTest": true
}
```

generated code for list object has multiple errors: Sample here:
```
 @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Pets Pets = (Pets) o;

        return ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
    }
```

equals method does not return anything.
hashCode - syntax error

Why is this happening? I cloned the latest version from repo.

**Comment by ashunam** [comment]
Re-tested with tag 1.5.23, but result is the same.

**Comment by stevehu** [comment]
@ashunam Thanks for the details explanation on the issue. I have reproduced the issue you found and created a folder in model-config with all the materials to explain the details. Please review and we can continue the discussion afterward. Thanks a lot for bringing it up.

https://github.com/networknt/model-config/tree/master/example/petstore-remote
