### ISSUE TITLE
GraalVM Native Image

### ISSUE THREAD

**Issue by archenroot** [networknt/light-4j#341]
Hi guys, have you tried already GraalVM native image compilation, it doesn't work with Spring for example well due to possibly lot of reflection usage which is not at moment still not fully supported by GraalVM, but maybe here is situation different.

**Comment by archenroot** [comment]
@miklish - yeah, but it looks like Spring itself already did a lot of work here with success:
https://jira.spring.io/browse/SPR-16991 
Although springboot still not fully supported.

There are ways to provide reflection mapping via JSON file to GraalVM so it can proceed... I am not lucky on Gentoo as we don't have yet package to install, but there is Graal Docker image which can be used for games with native compilation. I will give it a try with light4j just to see... and will come back.

**Comment by miklish** [comment]
Thanks! I'm curious to see if it works (and also curious to see what causes the errors if it fails)

**Comment by stevehu** [comment]
@archenroot Great insight on the topic. We will keep our eyes open as the development on this area is changing so fast. Thanks.

**Comment by stevehu** [comment]
There are a lot of requests from users these days and I think it is the time we take a look at the issue again. 

This link provides a lot of info on this topic. https://royvanrijn.com/blog/2018/09/part-2-native-microservice-in-graalvm/

**Comment by stevehu** [comment]
In a process to learn GraalVM and explore various components in light-4j on GraalVM, I have created [light-example-graal](https://github.com/networknt/light-example-graal)

**Comment by stevehu** [comment]
This has been done, and the example is in http-sidecar project.
