### ISSUE TITLE
make some of the server options configurable

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#351]
One of the customers asked if we can make the worker threads configurable as they have servers with many cores and want to have thousands of worker threads instead of hard-coded 200. 

I am thinking we should at least make the following configurable. 

* Buffer size
* Io threads
* Worker threads
* Backlog
* Always setdate
* Server string

As there are so many existing projects, we need to make sure that these default values are still for backward compatibility.

```
            server = builder.setBufferSize(1024 * 16).setIoThreads(Runtime.getRuntime().availableProcessors() * 2)
                    // above seems slightly faster in some configurations
                    .setSocketOption(Options.BACKLOG, 10000)
                    .setServerOption(UndertowOptions.ALWAYS_SET_KEEP_ALIVE, false) // don't send a keep-alive header for
                    // HTTP/1.1 requests, as it is not required
                    .setServerOption(UndertowOptions.ALWAYS_SET_DATE, true)
                    .setServerOption(UndertowOptions.RECORD_REQUEST_START_TIME, false)
                    .setHandler(Handlers.header(handler, Headers.SERVER_STRING, "L")).setWorkerThreads(200).build();

```

**Comment by ddobrin** [comment]
Agreed that Worker Threads config would aid teams who focus on mechanical sympathy and wish to extract max performance in their respective system.

These values can be set in server.yml with parameterized values using a "default value", which would allow both changes as well as backwards compatibility.

**Comment by jiachen1120** [comment]
@stevehu @ddobrin Hey! I have a question if the user configures the number of workerthreads to 0, or sets the serverstring to be empty. The server reported an error while binding to the port. So should we throw an exception directly when it detects that workerthread is 0 or serverstring is empty? Also, should the user be allowed to set iothread to 0? Although this allows the server to start normally, it should cause a bad debug situation.

**Comment by stevehu** [comment]
@jiachen1120 For the server name, we can set the default to "L" and only if it is specified in the server.yml with a value to replace it. Regarding the IO threads and worker threads, I think we can still set them as available processes * 2 and 200 as default if the passed in value is 0. I am expecting that most users won't know how to set it up.

**Comment by ddobrin** [comment]
I think we need to be careful with these settings. 

While server.yml is the natural place to set them, I think we need to set a special section "advanced settings, use with care", to draw attention to the special nature of these settings. 

If the use sets the value of the worker threads to 0, maybe we can default it to 1 and issue a WARN. It is just a suggestion. 
The alternative is to have for any 0 an exception thrown and a shut down

**Comment by stevehu** [comment]
How about we should put these into the server.yml at all. For advanced users, they can add them on their own.

**Comment by ddobrin** [comment]
If it would be by me only, I would take one of the 3 approaches, in order:
- use the documentation for "advanced settings", set defaults and allow teams to specifically go into the config and add them
- set an advancedconfig.yml, documented as "please be careful, use at your own risk".
- set the same configs in the server.yml at the bottom with the same extra warnings.

I would also say that adding into the certification process a validation would be very good.

It is a personal opinion

**Comment by jiachen1120** [comment]
@stevehu @ddobrin Good morning! Thanks for the ideas. I think the first method is better. Perhaps we should modify codegen to let server.yml add some documentation and configuration examples (key： value  specify the valid range, such as iothread should be greater than 0), but these are commented out. For users who don't want to change, everything is the same as before. For users who want to change, they can configure themselves according to the instructions and examples in server.yml. And we verify these self-configured values ​​to make sure they are valid, otherwise we will continue to use the default values. If you think this works. I will write it specifically as RFC. thanks!

**Comment by stevehu** [comment]
@jiachen1120 @ddobrin I think we are on the same page. I was even thinking to not update server.yml but only put these advanced options into the documentation. I guess only a small percentage of users will need to update them from the default values.

**Comment by jiachen1120** [comment]
@stevehu Make sense! I will finish the code part then do the documentation. Thanks

**Comment by jiachen1120** [comment]
@stevehu @ddobrin Hey! I just pull the request for both RFC and code. If these are acceptable, I will update the light-doc as well. Look forward to your review!
