### ISSUE TITLE
If handler path not implemented/wrong path , it will throw the 404 error code instead of 400.

### ISSUE THREAD

**Issue by sreenicibc** [networknt/light-4j#360]
API 30 -If handler path not implemented or wrong path , it will throw the 404 error code instead of 400.

**Comment by stevehu** [comment]
The #361 has been merged. Close this issue.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [If handler path not implemented/wrong path , it will throw the 404 error code instead of 400](https://trello.com/c/wYRmXPxi/73-if-handler-path-not-implemented-wrong-path-it-will-throw-the-404-error-code-instead-of-400)
