### ISSUE TITLE
Standardize repo line endings on LF

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-4j#365]
Currently this repo is mixed between LF (primarily) and CRLF (in a few scattered files).
We are seeing this issue manifest in PRs that are submitted with LF (with only a few lines changed) that get reported as the entire file being modified and makes it difficult to identify what's being modified.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Standardize repo line endings on LF](https://trello.com/c/Ea8PYb4D/72-standardize-repo-line-endings-on-lf)

**Comment by stevehu** [comment]
Merged #366.
