### ISSUE TITLE
TechEmpower benchmark

### ISSUE THREAD

**Issue by archenroot** [networknt/light-4j#369]
maybe you will be interested to include your framework here:
https://www.techempower.com/benchmarks/#section=code&hw=ph&test=update&l=cmh5z1-0

**Comment by stevehu** [comment]
It is there but they upgrade to the JDK 10 with the binary compatible with JDK8 and the numbers were way off. I have updated the test case with JDK 11 and now it is OK. The following link is a snapshot. 

https://www.techempower.com/benchmarks/#section=test&runid=58042695-831a-4a35-8c60-2b872a06f799&hw=ph&test=json
