### ISSUE TITLE
Unable to retrieve request body

### ISSUE THREAD

**Issue by mafabbri** [networknt/light-4j#37]
In my code:
`
HttpServerExchange.getRequestReceiver().receiveFullBytes((exchange, data) -> {
  //do stuff with the data
  DATA IS EMPTY
}, 
(exchange, exception) -> {
  //optional error handler
}
)
`
How can I get the body or the serialized JSON Object passed in my POST request? data is empty.
Thanks,
matt

**Comment by stevehu** [comment]
In the gernerated code we have a body parser middleware to parse the json body to map or list if content type is application/json. The object is in an exchange attachment and you can get it in you business domain handler. You can choose to use the raw map or list or convert to pojo. 
https://github.com/networknt/light-java/blob/master/body/src/main/java/com/networknt/body/BodyHandler.java

**Comment by stevehu** [comment]
And here is an example on how to get REQUEST_BODY in your handler. 

https://github.com/networknt/light-oauth2/blob/master/client/src/main/java/com/networknt/oauth/client/handler/Oauth2ClientPostHandler.java

**Comment by mafabbri** [comment]
REQUEST_BODY is null:
`
public class PathHandlerProvider implements HandlerProvider {

	public HttpHandler getHandler() {
		HttpHandler handler = Handlers.routing()

				.add(Methods.GET, "/isAlive", new HttpHandler() {
					public void handleRequest(HttpServerExchange exchange) throws Exception {
						exchange.getResponseSender().send("isAlive");
					}
				})

				.add(Methods.POST, "/signDocument", new HttpHandler() {
					public void handleRequest(HttpServerExchange exchange) throws Exception {
						Map<String, Object> body = (Map<String, Object>) exchange
								.getAttachment(BodyHandler.REQUEST_BODY);
						exchange.getResponseSender().send("body is null: " + (body == null));
					}
				})

		;
		return handler;
	}
}
`

**Comment by stevehu** [comment]
You code looks good. Do you have contentType application/json in your request header?

**Comment by stevehu** [comment]
And this link has info on how to debug on your IDE. Remember, the entire server is just a POJO so that you can debug into it. 

https://networknt.github.io/light-java/tutorials/debug/

**Comment by mafabbri** [comment]
Thanks Steve,
it works... was a problem of my pom.xml file. I have generated it with swagger-editor online tool.
Following the tutorial docs (https://networknt.github.io/light-java/tutorials/microservices/) I have genereted server code with swagger-codegen-cli and now request body is retrieved correctly and JSON mapped on my model object.

**Comment by stevehu** [comment]
I have to fork the swagger-codegen as the main project doesn't support Java 8 and I cannot convince them that JDK 8 can compile Java 7 code:) Also there is a docker image that can be used to generate code and steps are documented in this link.

https://networknt.github.io/light-java/tutorials/database/
