### ISSUE TITLE
Config Module - addressing gaps

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#371]
This is a placeholder issue and **should not be worked on, until further investigation occurs**.

A number of gaps have been identified in the Config Module. 
Items will be listed here, before any work can commence:

1. **Config module returns primitive or object values, dependent on the usage of an environment variable or not**
1.1. environment variable enableVerifyJwt: ${openapiSecurity.enableVerifyJwt:false} returns the boolean primitive
1.2 enableVerifyJwt: false returns the object boolean

Linked issue: https://github.com/networknt/light-rest-4j/issues/70

2. **Values set with environment variables are not trimmed** and lead to failure: httpPort: ${server.httpPort:8080} is interpreted different than httpPort: ${server.httpPort:  8080} and the second fails

Linked issue: https://github.com/networknt/light-codegen/issues/212 

3. **A change is required to support the change which has been made in light-codegen to address the exclusions list, aka files for which environment variables can't be used**. 

The issue #368 "Allow exclusion list of files which should not check/allow for environment variable setting" is the Config module piece of work which should take the exclusions list into consideration at runtime.
Linked issue: https://github.com/networknt/light-4j/issues/368

**Comment by ddobrin** [comment]
The issue is open to be worked on

**Comment by jiachen1120** [comment]
@ddobrin For the second point: Values set with environment variables are not trimmed and lead to failure: httpPort: ${server.httpPort:8080} is interpreted different than httpPort: ${server.httpPort: 8080} and the second fails

The yaml parse does not allow double mapping or more mapping appeared in one line. Take above example as a case, "httpPort:" will mapping to "${server.httpPort: " and then yaml find there still something "8080}" need to be mapped. then yaml will throw an example: mapping values are not allowed here.

So, I think there should not use space after the colon, and people should always using the first format you mentioned. what do you think?

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Config Module - addressing gaps](https://trello.com/c/c2w4YhtI/77-config-module-addressing-gaps)
