### ISSUE TITLE
light-java performance

### ISSUE THREAD

**Issue by selforganized** [networknt/light-4j#39]
I was looking at the web framework benchmark (https://www.techempower.com/benchmarks/previews/round14). light-java has really good performances in Fortune & Single Query. But in Multiple Queries & Data Updates light-java's performances are less than exemplary, falling behind even some Ruby & Python frameworks. Any particular reasons why that is so?

**Comment by stevehu** [comment]
@selforganized Thanks for the link. I created these test cases in a weekend and never test them myself as I am not familiar with the toolset and environment. Multi-Queries/Updates need some optimization to maximize utilization of all cores(I don't know how many cores they have). The plaintext and json results are surprise for me as the numbers are lower than my laptop. Fortunately, there are logs available and I am looking into it now.

**Comment by stevehu** [comment]
Submitted a pull request to tune the performance of multiple queries/updates but there are still a lot of things to do. I just learned that multiple updates batch is allowed from the spec. Need to read the spec. carefully:)

**Comment by stevehu** [comment]
This should be addressed in round 15 as a new pull request has been submitted to techempower.
