### ISSUE TITLE
Backwards incompatible changes: client module - release 1.5.29

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#397]
The OauthHelper class exposes the getToken() method.
It returned a TokenResponse and it returns a different response at this time: Result<TokenResponse>, where Result is: com.networknt.monad.Result;

Code at my client fails with this change and it makes the release backwards incompatible. 

The fix should include:
- documentation for the change to getToken()
- sample code light-example

**Comment by ddobrin** [comment]
Change linked to closed issue #41

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Backwards incompatible changes: client module - release 1.5.29](https://trello.com/c/CrLP0AZ7/96-backwards-incompatible-changes-client-module-release-1529)

**Comment by ddobrin** [comment]
Issue closed:
fixed by https://github.com/networknt/light-4j/pull/399
