### ISSUE TITLE
setup Travis cron to run integration test daily

### ISSUE THREAD

**Issue by lanphan** [networknt/light-4j#405]
I check Travis build history and don't see any build which have integration test. It seems we haven't setup cron to run integration test, do we?
I suggest to setup cron to make sure all tests (unit tests + integration tests) are run fully. In addition, let's have it so that I can check my PR https://github.com/networknt/light-4j/pull/404 run well or not.

**Comment by lanphan** [comment]
Link to setup cron on Travis: https://docs.travis-ci.com/user/cron-jobs/
I think we can setup 2 crons for light-4j, for develop and master branch.

**Comment by stevehu** [comment]
Great ideas. None of us is an expert on Travis and I don't even know it can set up cron-jobs. Internally, we are using light-bot to build and test multiple repositories. Do you know if there is a way to integrate with light-bot from Travis? Thanks.

**Comment by lanphan** [comment]
Travis doesn't support inter-repositories build, so that I don't think it's possible.
However, I come up with another way:
1. Setup Travis build (unittest only) for each and every light-* repositories. We just do once.
2. For light-bot (or light-config-test?), we'll setup daily cron-job for this. This cron will run script similar mentioned in this article: https://hiddentao.com/archives/2016/08/29/triggering-travis-ci-build-from-another-projects-build/ (using environment to specify running integration test also), therefore, we just need to setup cron for 1 project only.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [setup Travis cron to run integration test daily](https://trello.com/c/0SnRQtOW/101-setup-travis-cron-to-run-integration-test-daily)
