### ISSUE TITLE
Maven build error on eclipse

### ISSUE THREAD

**Issue by HatanbaatarG** [networknt/light-4j#406]
Can not find symbol error on compile handler.handlerprovider. I have tried to run light example mongodb project. Below is the screenshot pls. 
https://drive.google.com/file/d/1RD0PbB0rPlia5zJTfPQ7VBQJDazJTgGA/view?usp=drivesdk

**Comment by HatanbaatarG** [comment]
It is a question I guess

**Comment by stevehu** [comment]
The Mongo example was created upon a request from the community as a demo but we don't have any experience on the database. I was only started but not completed as we need help. From the error I think it is due to the version of framework. We will take a look once we have time. Thanks for bringing it up.

**Comment by HatanbaatarG** [comment]
The problem went away after handler codes folder copied in project src but test failed with following error:
java.util.ServiceConfigurationError: com.networknt.server.HandlerProvider: Provider com.networknt.database.PathHandlerProvider not a subtype

**Comment by HatanbaatarG** [comment]
solved by changing import com.networknt.handler.HandlerProvider; to import com.networknt.server.HandlerProvider;

**Comment by stevehu** [comment]
https://github.com/networknt/light-example-4j/issues/85

**Comment by stevehu** [comment]
@HatanbaatarG Yes. That is the exact issue. I have updated the light-example-4j develop branch so it can be compiled now. As I am not familiar with Mongo, I am wondering if you could help to complete this example and upgrade to the latest version of the framework later on.  I know a lot of people are using Mongodb and a tutorial would be really helpful for those users. Thanks.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maven build error on eclipse](https://trello.com/c/fLbevirs/102-maven-build-error-on-eclipse)

**Comment by HatanbaatarG** [comment]
Ok, made a file change for testing.
