### ISSUE TITLE
Support configure for allowUnescapedCharactersInUrl in undertow.

### ISSUE THREAD

**Issue by hebutliu2010** [networknt/light-4j#412]
The old version of ligth4j(1.3.5) support non-ascii characters for query parameter, but new version of ligth4j dependent on new version undertow, this feature is no longer supported.
https://github.com/undertow-io/undertow/commit/d63b767010133d574196740892a845c1375e8bed#diff-4d93e9a9cf8b37e2bc2b882ae2bca189

We can add configure for allowUnescapedCharactersInUrl.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support configure for allowUnescapedCharactersInUrl in undertow](https://trello.com/c/l6VJx5cr/168-support-configure-for-allowunescapedcharactersinurl-in-undertow)

**Comment by hebutliu2010** [comment]
Thank you very much.

**Comment by stevehu** [comment]
@hebutliu2010 I have added the following comment on the document site and you need to be aware that there is a security risk to enable this feature. 

```
 # Flag to set UndertowOptions.ALLOW_UNESCAPED_CHARACTERS_IN_URL.
 # Please note that this option widens the attack surface and attacker can potentially access your filesystem. 
 # This should only be used on an internal server and never be used on a server accessed from the Internet. 
 allowUnescapedCharactersInUrl: true

```
