### ISSUE TITLE
Integrate decryption module in all retrievals of config

### ISSUE THREAD

**Issue by dz-1** [networknt/light-4j#413]
Originated from API-49:
Investigation Required
Currently when config is retrieved it needs to be done so with explicit instruction to support decrypting values. This could lead to some modules not supporting encryption/decryption and could result in issues.

**Comment by stevehu** [comment]
In the beginning the ideas is to group all the secrets into one file secret.yml and only enable decryption for that file. Apparently, it won't be enough and cause a lot of confusions for developers. If we are decrypt for every config file, then I think we should retire the secret.yml. What do you think?

**Comment by dz-1** [comment]
Personally, I think putting secrets in one file is not bad and we can leave that file as is.
The fix of this issue gives developers more flexibilities in organizing files.

 @NicholasAzar What do you think?

**Comment by NicholasAzar** [comment]
Moving those fields around could lead to a breaking change though right? Currently I can think of the following places where we have secrets external to secret.yml; metrics.yml, server.yml, basic-auth.yml.. looking at those I don't know if it's feasible to move everything secret to secret.yml.

**Comment by stevehu** [comment]
We can still keep the secret.yml but make it deprecated and removed in 2.0.x later on. For an existing application, if they are using secret.yml, they must load it explicitly. The question is should we move those secrets back into individual config files.

**Comment by ddobrin** [comment]
if the values are moved back into individual files, we need to think about this being documented very very clearly, as many of these "secret" values are set in the secret.yml + already set in the values.yml as overwrites.

Consumers would have to move them all back to their individual config files and, if you have a larger number of APIs, it has a ripple effect across all of them.
