### ISSUE TITLE
Dynamic Port binding not working as expected in light4j

### ISSUE THREAD

**Issue by kumasath** [networknt/light-4j#415]
Please find the bug details below.

Qualified Java Name: com.networknt.server.Server.bind(HttpHandler, int)

Runtime exception is thrown while binding the port if the port is not available. 
Expected behaviour is to loop through the port range and start with the one which is available. Thanks.

**Comment by NicholasAzar** [comment]
@jiachen1120 I'll work on this as it's part of an urgent change for this weekend

**Comment by jiachen1120** [comment]
@NicholasAzar Good afternoon! I am sorry that I have not fulfilled my duties to complete the task you handed in. I just did a test and found that there may still be some areas to improve on this issue. So, I made this PR: https://github.com/networknt/light-4j/pull/417
