### ISSUE TITLE
add TTL to the consul check register for ttlCheck option

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#420]
There are three options to allow Consul to update the health of individual service instance and they are defined in the consul.yml file. For most of the cases, we encourage users to use httpCheck as it is well tested and very reliable. However, for certain situations, the service instance cannot be accessed by the Consul cluster/agent, then ttlCheck might be used. Instead of letting Consul call your service, the service will call Consul instead in this case. 

For the other two options, httpCheck and tcpCheck, only one interval needs to be sent to the Consul so that Consul will make calls based on this interval. For ttlCheck as the call is initialized by service itself, we actually need two values to control how the health check works. 

TTL: This is the value that is sent to the Consul to indicate the timeout when Consul consider the service is not healthy. 

Interval: The service will access the check endpoint of Consul at this interval. 

The rule is that the TTL must be equal or greater than the Interval. This allows Consul to received a call before the TTL is reached. 

In the current implementation, we are getting the interval from consul.yml and use that as TTL value to send to Consul for the check register. We also use the same value to trigger the calls to consul from the service instance. As there two values are the same, we don't have any buffer in the case the check request is not handled in time. 

The recommendation is to add another ttl value for the consul.yml only for ttlCheck option and make this value bigger than the interval in the same config file. 

For example, if we set the interval to 10s, we can set the TTL 15s. So the Consul server will check if there is a call from the service every 15s and the service will call to the Consul very 10s. 

https://www.consul.io/api/agent/check.html

**Comment by BalloonWen** [comment]
The actual reason is the "checkInterval" setting in consul.yml doesn't work for TTL, the heartbeat for TTL was not depended on that.
Now: the "checkInterval" will work for all TCP, HTTP, TTL in registration to Consul, but when TTL model, the heartbeat to send to Consul will be 2/3 of "checkInterval"

**Comment by stevehu** [comment]
@BalloonWen Good findings. I think your solution is much better than putting two values into the consul.yml I originally thought. Thanks.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add TTL to the consul check register for ttlCheck option](https://trello.com/c/n032XdUL/119-add-ttl-to-the-consul-check-register-for-ttlcheck-option)

**Comment by kumasath** [comment]
Hi Steve,
As discussed, Consul registry failed with 2 pods.  Please find the stacktrace and consul.yml file below.
This issue can be simulated in Openshift container. Thanks

**Exception stackTrace:**
[2019-03-29@17:05:31.753][ERROR][][][][pool-3-thread-3][c.n.consul.client.ConsulClientImpl.checkPass:113] - CheckPass request exception
java.lang.Exception: Failed to checkPass on Consul: 500:Unknown check "service:*.*.*.*:com.example.api1-1.0.0:15211"
	at com.networknt.consul.client.ConsulClientImpl.checkPass(ConsulClientImpl.java:110)
	at com.networknt.consul.ConsulHeartbeatManager$HeartbeatJob.run(ConsulHeartbeatManager.java:173)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)





**Consul.yml file:**
consulUrl: http://consul.example.com:8500
deregisterAfter: 1m
checkInterval: 10s
tcpCheck: false
httpCheck: false
ttlCheck: true

**Comment by stevehu** [comment]
@kumasath From the error message, it looks like the service is not registered on the Consul. Could you please paste your server.yml? Also could you please check if you can find the service instances on the consul UI? Thanks.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feat/light 4j/#420 fixed TTL check](https://trello.com/c/POYPx21v/125-feat-light-4j-420-fixed-ttl-check)

**Comment by stevehu** [comment]
Although this issue has been resolved by a pull request; however, we have reported that he ttlCheck is not stable when setting the interval to 10s. It is much more stable when it is set to 30s.
