### ISSUE TITLE
Fix status merge

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#425]
Currently, the status merge cannot work properly, a small change is needed. 

Original status.yml contents would lose after merging.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix status merge](https://trello.com/c/P5rKkZLM/110-fix-status-merge)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix status merge](https://trello.com/c/U3o8dgUb/120-fix-status-merge)
