### ISSUE TITLE
update pom.xml to support release of SNAPSHOT version

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#459]
For our users, they are using the released version; however, for our platform developers, it might be convenient to use the snapshot version for the dependencies instead of building all repositories locally with light-bot. Let's find out how to config the pom.xml to release the snapshot version.

**Comment by santoshaherkar** [comment]
Yes we really need to introduce snapshot versions which would be very helpful for developers. 
To enable snapshot version, all we have to do in POM file is change version to say 1.6.0-SNAPSHOT to mark it as the SNAPSHOT (under development) version. Then every time we run **mvn deploy**, it will deploy version like 1.6.0-SNAPSHOT-{timestamp}-{counter} to central repository/artifactory. Developers can continue using version 1.6.0-SNAPSHOT which will fetch latest version for 1.6.0-SNAPSHOT-* from central repo. By default maven downloads given SNAPSHOT version once per day but can be configured to check central repo every time we run the build. 

Once the development is completed for v1.6.0, to release it as a Stable Version, here are the steps we have to follow:
1. Remove -SNAPSHOT from the version in POM file
2. Run **mvn clean install** (which will build and deploy jar in local .m2 repo & we can verify the build)
3. Run **mvn deploy** (which will deploy release version into central repository)
4. Change version in POM file to 1.7.0-SNAPSHOT to start developing new features (change minor version to reserve patch versions for bug fixes on 1.6.0)

We can use maven release plugin to do all these steps for us but this plugin is not that reliable and its hard to recover if something fails.  So I recommend doing it manually.

**Comment by stevehu** [comment]
@santoshaherkar Thanks a lot for the nice step by step explanation. I have updated most of the repositories to simplify the dependencies version with only version.light-4j in the properties. This significantly simplifies the version-upgrade light-bot configuration to update all repositories in batch pre-release and post-release. I will try it out with your step to update all versions to -SNAPSHOT.

**Comment by stevehu** [comment]
While I was working on the light-bot configuration, I realized that we cannot blindly update all related repositories to a snapshot version in the master branch. For example, the light-codegen is used by a lot of users to scaffold projects on the latest released version and light-example-4j contains all the examples upgraded to the latest release so that users can try them out. I am thinking to create release branches for these repositories and make them as default branch and update the master branch with snapshot versions to ensure our tests are on the same branch consistently. What do you think?

**Comment by stevehu** [comment]
The first snapshot version 1.6.1-SNAPSHOT was released last night. For more details regarding to the implementation, please visit https://doc.networknt.com/tool/light-bot/task/release-snapshot/
