### ISSUE TITLE
Incorrect status code

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#466]
ERR12049:
 statusCode: 400
 code: ERR12048
 message: PROVIDER_ID_INVALID
 description: Provider id invalid

should read:
ERR12049:
 statusCode: 400
 **### code: ERR12049**
 message: PROVIDER_ID_INVALID
 description: Provider id invalid

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Incorrect status code](https://trello.com/c/gZfd5fpR/171-incorrect-status-code)
