### ISSUE TITLE
Do not send chunked as the TRANSFER_ENCODING header in Oauth Request

### ISSUE THREAD

**Issue by jsu216** [networknt/light-4j#470]
The OauthHelper always send "chunked" as the TRANSFER_ENCODING header when requesting for Oauth Token. This header affects the behavior of some Oauth Servers that can cause failed response.
We need to either remove this header or to put this as an option in the client.yaml for backward compatibility.

**Comment by NicholasAzar** [comment]
@jsu216 Hey, from looking at the code it's seeming like this was addressed in 1.6.0.. have you been seeing it working otherwise?

**Comment by jsu216** [comment]
Yes, it is in. But the changes in the light-router was not sync with 1.6.0 but 1.6.1.

**Comment by stevehu** [comment]
@jsu216 Any difference that impacts this functionality between 1.6.0 and 1.6.1-SNAPSHOT?

**Comment by BANZAY2018** [comment]
Sorry bro

**Comment by jsu216** [comment]
Solved in 1.6.0
