### ISSUE TITLE
Oauth enhancement and extension / support custom claims

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#472]
In order to meet the various demands of users, a more generic method to get JWT may needs to be provided, and users should be able to choose multiple caching ways. 

In addition, the client module should also support the custom claim, and the user can add an encoded custom claim to their request header by using Base64Encoder. This header will be verified by the client -- whether it can be successfully decoded. Then it is encoded again and added to the request body sent to the oauth server. At the same time, the custom claim will also be part of the cache key.
RFC: https://github.com/networknt/light-rfcs/blob/jiachen1120-patch-1/light-4j/0020-oauth-enhancement.md

**Comment by stevehu** [comment]
As discussed, this impacts security and shouldn't be implemented.
