### ISSUE TITLE
client module enhancement to use CompletableFuture to handle two or more threads  asynchronous computation

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#480]
client module implement to use CountDownLatch to handle threads wait. 
Add some new methods to java CompletableFuture to handle two or more threads  asynchronous computation

**Comment by jefperito** [comment]
Is There any way create unit tests?

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add new feature method for client module.](https://trello.com/c/bWKfqfOg/176-add-new-feature-method-for-client-module)
