### ISSUE TITLE
Consul service discovery error when discover same services with different env_tag

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#482]
If specify an env_tag which registered in Consul, it routes to it and cache it, which means, doesn't matter what env_tag you put later on, it returns the cached one.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Consul service discovery error when discover same services with different env_tag](https://trello.com/c/cpE7Xne1/178-consul-service-discovery-error-when-discover-same-services-with-different-envtag)

**Comment by ddobrin** [comment]
@jiachen @NicholasAzar @stevehu : this issue is breaking behavior at my client

**Comment by stevehu** [comment]
@ddobrin Thanks for bringing it up. I have opened a new issue #491 to address it.
