### ISSUE TITLE
system property light-4j-config-dir does not accept windows paths

### ISSUE THREAD

**Issue by dz-1** [networknt/light-4j#483]

**Comment by stevehu** [comment]
@dz-1 Nice catch and fix. Although we are all working on Linux or Mac, there are still a lot of developers are working on Windows. Thanks.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [system property light-4j-config-dir does not accept windows paths](https://trello.com/c/d6E8YLcU/187-system-property-light-4j-config-dir-does-not-accept-windows-paths)
