### ISSUE TITLE
Any plan to create tools like "jhispter" to help build microservices?

### ISSUE THREAD

**Issue by hydra1983** [networknt/light-4j#5]
I have read the doc hosted in https://networknt.github.io/light-java/. Light java will be a great framework to help developers create microservices with good architecture. I have being using Jhispter for a while. Although it's based on spring, which is too heavy for microsevices, the speed to create a project from scratch is still astonished me a lot.

**Comment by stevehu** [comment]
I never used these generators before and they look pretty good. In Light-Java we are using [swagger-codegen](https://github.com/networknt/swagger-codegen) to generate a running project with OpenAPI specification. The swagger_codegen is template based just like Yo so I think we can add more generator in a long run. For client side single page applications, jhispter can be used I think. I also have a [project](https://github.com/networknt/react-schema-form) to generate react forms at runtime based on JSON schema and I am using it very heavily for my own projects.

**Comment by stevehu** [comment]
I have found some many limitations with swagger-codegen and thinking about to write a generator with more flexibilities. looking into jhispter.... Thanks for pointing me to this direction.

**Comment by stevehu** [comment]
[light-codegen](https://github.com/networknt/light-codegen) has been created and all our dev teams are switched.
