### ISSUE TITLE
Adding auto test for consul registry and discovery 

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#502]
Currently, a mock consul may cannot fully cover the real usage cases of consul.  To integrate with something like this https://www.baeldung.com/docker-test-containers to start a real consul server in our tests so we can automate a bit more.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adding auto test for consul registry and discovery](https://trello.com/c/KmqMQvwL/254-adding-auto-test-for-consul-registry-and-discovery)
