### ISSUE TITLE
Resolve differences between loading trustStore and keyStore credentials

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#504]
We are using light-consumer-4j-1.5.21.jar to connect to micro-service APIs. We trying to establish 2-way TLS connection to micro-services, noticed there is a difference in the way truststore and keystore are loaded.
 
Please refer to Http2Client > createSSLContext() -
 
While loading a truststore, it looks first into System properties for truststore path and password (javax.net.ssl.trustStore and javax.net.ssl.trustStorePassword), if not found, it looks in secret.yml.
 
For keystore properties, it always look in secret.yml. was there any reason this was done the way it is? Can we make a change to have the keystore config read from system property as well?

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolve differences between loading trustStore and keyStore credentials](https://trello.com/c/Q2wDavVr/212-resolve-differences-between-loading-truststore-and-keystore-credentials)
