### ISSUE TITLE
Make sure request/responses for consul, oauth, and api calls are logged with debug

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#506]
In the case of consul I believe the request could be pieced together with the results of previous log statements, but we don’t currently output the entire request/response as a single entry.
For the OAuth calls and the ones to downstream APIs, although there are a few, on looking through the code our log statements are definitely more sparse… If required, the calls to the downstream APIs and their responses can be logged from your application code.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure request/responses for consul, oauth, and api calls are logged with debug](https://trello.com/c/QKsRUkQl/250-make-sure-request-responses-for-consul-oauth-and-api-calls-are-logged-with-debug)
