### ISSUE TITLE
Sanitizer mangles content

### ISSUE THREAD

**Issue by srl295** [networknt/light-4j#51]
The Sanitizer is too aggressive and mangles content strings. I understand the intent, but had to disable it to retrieve the original strings sent in. In my case I am passing an XML document as a string.

Before disabling sanitizer: `<?xml version=\"1.0\"?>`
After disabling sanitizer: `<?xml version="1.0"?>`

In generated `src/main/resources/META-INF/services/com.networknt.handler.MiddlewareHandler`
> `#com.networknt.sanitizer.SanitizerHandler`

**Comment by stevehu** [comment]
The sanitizer is designed for JSON and I never tested it with XML. Have what is your content-type? application/xml? If yes, I can do something to disable it if the content is XML automatically. Disable it is a good option too. I actually don't think it is very useful for most RESTful APIs anyway, only for certain APIs that collected data might be displayed on browser somehow. It should be an optional middleware handler in my mind. Thanks for bring it up and I will revisit it soon.

**Comment by srl295** [comment]
@stevehu it's just a string parameter in a JSON object such as `{ "data": "<?xml…." }`  The problem is that the sanitizer modifies strings, so my light-java handler doesn't see the string as it was sent from the swagger caller.

As I said, I understand why sanitizers are used, to neutralize harmful content. It's just not applicable in my case.

**Comment by stevehu** [comment]
@srl295 This issue has been reported from time to time and the general recommendation is to use this middleware handler only when you are rendering web pages directly with user input like blogs or forums. I have updated the document and I think we can close this issue for now. Thanks.
