### ISSUE TITLE
Add support of JsonWebKey in JWT key verification

### ISSUE THREAD

**Issue by jsu216** [networknt/light-4j#510]
Details in the RFC:
https://github.com/networknt/light-rfcs/blob/master/light-4j/0021-Support-JsonWebKey-in-JWT-key-verification.md

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support of JsonWebKey in JWT key verification](https://trello.com/c/fC0tYptw/216-add-support-of-jsonwebkey-in-jwt-key-verification)
