### ISSUE TITLE
Parameterized value in Config can not be overwritten 

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#512]
The Config module supports parameterized values.

In case a value is defined, and a default is provided, in any config file, the value can be overridden in values,yml

The following doesn't work:
server.yml
environment: ${server.environment:dev}

can be overridden by:
server.environment:test1

however can't be reset to null, as in:
server.environment:
or
server.environment: null

The behaviour is uneven, you can define the variable as:
environment: ${server.environment}
and set it to null as:
server.environment:

In this case, you can set it to null.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Parameterized value in Config can not be overwritten](https://trello.com/c/uz8ju0g9/213-parameterized-value-in-config-can-not-be-overwritten)
