### ISSUE TITLE
make the sanitizer handler context aware by config

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#514]
The current sanitizer handler blindly applies the JavaScriptSource encoding for the body and it might not be the right thing to do based on the context of the API. The library was designed for JSP and server-side rendering with a clear context about the data it is trying to encode. In the API world, we don't have the context available. In order to apply the right encoding for the right API, we need to allow users to pass in a context from the sanitizer.yml so that the right encoding will be applied for the body of the request. 

We also need to explore if there are new libraries available to replace the https://github.com/OWASP/owasp-java-encoder

https://github.com/networknt/light-4j/issues/513

**Comment by jefperito** [comment]
Do you have any idea how to define a context?

i did not find stable and active libraries for XSS in java.

**Comment by stevehu** [comment]
I think it is the service developer's responsibility for defining the context in the configuration. Every service is dealing with some type of data and the developer knows which type of encoding is needed.

**Comment by ddobrin** [comment]
I agree that the development team should be allowed to set the encoding. 

My client has a service they wish to build where they were asking for this

**Comment by stevehu** [comment]
When doing sanitization for the XSS, we need to know what kind of data we are dealing with and apply certain type of encoding based on the data type and attribute as well as the position in the json. As a framework developer, we need to consider all possible scenarios but we cannot predict the use cases. We need the application developers to provide additional info to apply XSS encoding and we call it context since the app developers know what kind of data they are dealing with. The context can be passed to the sanitizer hander through the sanitizer.yml config file so that we know what kind of encoding is best for the application.

**Comment by jefperito** [comment]
we can create a new attribute in config yml, where receives a list of json properties, so apply encode only these properties, or a little bit elaborated a list of [jsonpath](https://restfulapi.net/json-jsonpath/).

**Comment by stevehu** [comment]
Good idea. That gives us even fine-grained control on which field to be encoded and what kind of encoding is needed.

**Comment by jefperito** [comment]
i've started a new branch for resolve this one

https://github.com/networknt/light-4j/tree/514-sanitizer-new-config-properties

**Comment by jefperito** [comment]
how about developers configure your own encoding? 

I'm thinking of allowing developers to configure their encoding engines implementing this interface i've created:

https://github.com/networknt/light-4j/blob/514-sanitizer-new-config-properties/sanitizer/src/main/java/com/networknt/sanitizer/enconding/Encoding.java

user to register that class (similar to ModuleRegistry), so at startup of sanitizer module, it recovery and instance that one.

**Comment by stevehu** [comment]
I think this should work; however, it might require the developers to know how to implement the encoding.  What we can do is to implement all useful encodings and let developers choose which one is the best for their use case. If none of them are suitable, then they can implement their own encoder.

**Comment by jefperito** [comment]
What we got so far,

2 properties in sanitizer.yml:
    * attributesToIgnore: list of attributes to ignore encoding.
    * encoding: kind of encoding selected (used to select ).

EncoderRegistry: class that register an encoder that a dev can add it.

Which features can we add to list?

**Comment by stevehu** [comment]
@jefperito This is a very good starting. If the body has too many attributes, the ignore list will be too long to be practical. I think we can provide both include and exclude list to cover different type of body data. Also, I am not sure if we should support a group of attributes are encoded with encoder1 and another group of attributes are encoded with encoder2.

**Comment by jefperito** [comment]
good point of view about keep lists of include and exclude properties.

**Comment by jefperito** [comment]
Sorry for the delay (now i have a newborn at home)

ive created 2 parameters:

attributesToAppreciate: attributes for apply encoding (ignore everything else)
attributesToIgnore: attributes for ignore encoding (apply everything else)

**Comment by stevehu** [comment]
@jefperito Congratulations!!! It is open source and we don't have deadlines :) I have asked other member to review and hope will merge soon. Thanks.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [make the sanitizer handler context aware by config](https://trello.com/c/TQ0ZLkO9/272-make-the-sanitizer-handler-context-aware-by-config)
