### ISSUE TITLE
NullPointerException when doing serviceToUrl

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#518]
When a service can't be found in the serviceToUrl method, a NullPointerException is thrown. Not sure if this is the best thing to do, as it would be more expected to simply return null. 
 
In cases where a connection couldn't be made or something like that, a different exception would make sense.

**Comment by stevehu** [comment]
An NPE is definitely not a good idea. We should log a ClientException with meaningful context message like with service cannot find the instance. 

One thing that we need to think about is the retry logic as the target service might be in a process to restart by the orchestrator like Kubernetes. We can also implement the capability to define a dummy return for each non-critical unavailable services.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [NullPointerException when doing serviceToUrl](https://trello.com/c/fqxLQAbT/317-nullpointerexception-when-doing-servicetourl)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [e89c5befcea144b4b00c53ecc38847809a99250d](https://trello.com/c/NumTpyMw/318-e89c5befcea144b4b00c53ecc38847809a99250d)
