### ISSUE TITLE
Server Keystore should not fall back to default

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#519]
Example:
User configures their HTTPS server keystore but puts in the wrong filename, when the server doesn't find it, it will default to the open source test keystore and will run normally.
This is a security issue.

A possible solution: migrate .keystore and .truststore from main folder to test folder

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Server Keystore should not fall back to default](https://trello.com/c/bE9KlEV8/256-server-keystore-should-not-fall-back-to-default)
