### ISSUE TITLE
Consul connection freezing bug

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#523]
In the process of consul lookup service. There is only one connection per consul client. This means that all lookup threads need to share this connection. And once a service is found successful. This connection will hang and keep listening to the consul until the state of the corresponding service changes. Thus, when other lookup threads (different services) send requests to consul, the request will be placed into the queue until the first service state change or timeout. 

And @BalloonWen and I think the correct performance should be that each lookup thread should have its corresponding connection instead of sharing a connection. By doing this, one lookup hang would not influence others.

**Comment by stevehu** [comment]
The consul client was designed for HTTP/2 only as the HTTP/2 connection is multiplex. You need a connection pool if using HTTP/1.1. I think the first thing we need to find out why HTTP/2 stops working.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Consul connection freezing bug](https://trello.com/c/nrIxOVm6/247-consul-connection-freezing-bug)
