### ISSUE TITLE
clean up same class in different package, Http2ClientCompletableFutureNoRequest

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#526]
class:
Http2ClientCompletableFutureNoRequest
Http2ClientCompletableFutureWithRequest
were moved from io.undertow.client.http to com.networknt.client.http
but they were recreated by mistake in some previous pull requests
now need to clean it up.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [clean up same class in different package, Http2ClientCompletableFutureNoRequest](https://trello.com/c/OVhvXbOs/249-clean-up-same-class-in-different-package-http2clientcompletablefuturenorequest)
