### ISSUE TITLE
Add service name to Server configuration

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#530]
There are occasions, looking at future services, where a unique service name is valuable. 

It can be used in microservices to associate a given name to a service with the respective configuration or as a key within the configuration of a particular domain.

It can be used for auditing purposes, for example, or as a service identifier when producing events.

This service name is independent from the serviceID and can be set optionally.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add service name to Server configuration](https://trello.com/c/lOvaxcgt/252-add-service-name-to-server-configuration)
