### ISSUE TITLE
Add OpenTracing support for observability

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#536]

**Comment by stevehu** [comment]
The Jaeger tracer is implemented for now and it is very easy to add Zipkin but I am leaning to Jaeger more as it is a replacement of Zipkin. Until our users ask for Zipkin, we are not going to spend time on it; however, a user's contribution is welcome. 

Skywalking implementation is another one that we want to do but it has more features than the OpenTracing API. Need more time to learn and it is very popular in China. 

https://github.com/networknt/light-4j/issues/167

**Comment by chenyan71** [comment]
I will take a look Skywalking implementation

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add OpenTracing support for observability](https://trello.com/c/SelLej6A/270-add-opentracing-support-for-observability)
