### ISSUE TITLE
Deprecate certain public APIs across the framework

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#547]
We've had a few instances where users of the framework would access public variables or methods that should not have been made accessible.
We should look through all public APIs to ensure that they are deprecated if they should not be accessed externally and ensure we have a decommissioning date included.

**Comment by stevehu** [comment]
Totally agreed. Let's mark them deprecated in 1.6.x branch and remove them in the 2.0.x branch.

**Comment by jefperito** [comment]
i can help you if you wish for that.

**Comment by stevehu** [comment]
@jefperito I have invited you to the networknt slack channel and you can chat with @BalloonWen there. There are a lot of modules and repositories that need to be reviewed. Thanks.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deprecate certain public APIs across the framework](https://trello.com/c/kWXCQYYN/319-deprecate-certain-public-apis-across-the-framework)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deprecate certain public APIs across the framework](https://trello.com/c/Cl1UCazn/340-deprecate-certain-public-apis-across-the-framework)
