### ISSUE TITLE
test: use random port

### ISSUE THREAD

**Issue by srl295** [networknt/light-4j#55]
I'm a little concerned with `http://localhost:8080/…` being hard coded in the generated tests. I did have an issue where the tests can't run if the development server is running locally.

It seems like the `TestServer` class could assign a random port… and the tests could query `TestServer.getInstance().getBaseUrl()` or something. 

At the least, the test server should run on a different port. (Maybe a `src/test/resources/config…` file will do this). I'm going to try that approach.

**Comment by stevehu** [comment]
Currently we are using a customized swagger-codegen to generate the project and it is not flexible at all as the only input is the swagger and a couple of fields. I have built a new generator that support not just light-java-rest but light-java-graphql, light-java-hybrid. Also, you have have more config parameters than before to fine tune your generated code. For example, you can specify the port and testPort etc. Take a look at https://github.com/networknt/light-codegen

I have migrated the light-java-rest to the new generator and working on the docker image for the command line tool. Once that is done, we are going to enhance the generator to put more options in. For example, database support etc. Let me know if you have questions and feedbacks. Thanks.

**Comment by stevehu** [comment]
As part of the enhancement, we need to make sure that light-codegen has options for all framework to config http port, https port and test ports. This include, light-java-rest, light-java-graphql and light-java-hybrid-server.

**Comment by stevehu** [comment]
The latest version of light-codegen support customized http and https ports in the config.json. For more details, please see the [tutorial](https://networknt.github.io/light-rest-4j/tutorial/ms-chain/)
