### ISSUE TITLE
add hotspot monitor for prometheus metrics middleware handler

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#566]
add hotspot monitor for prometheus metrics middleware handler.
We had based restful request/ response prometheus monitor implemented before. 
Need add  hotspot monitor for prometheus

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add hotspot monitor for prometheus metrics middleware handler](https://trello.com/c/Al3lAUvm/289-add-hotspot-monitor-for-prometheus-metrics-middleware-handler)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add hotspot monitor for prometheus metrics middleware handler 1.6.x](https://trello.com/c/xxBjPmVS/528-add-hotspot-monitor-for-prometheus-metrics-middleware-handler-16x)

**Comment by stevehu** [comment]
@chenyan71 I have cherry-picked the PR to the 1.6.x branch. Thanks a lot for raising it up.
