### ISSUE TITLE
Pluggable config loading strategy

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#571]
Make current config module loading strategy as pluggable features so that clients can inject their own implementation of config loader

Notes: different from config server one. This issue aims to enhance current config module to support multiple config loading ways.

For example, some users prefer to use a spring-like configuration that uses a single configuration file instead of multiple configuration files for each module. By providing this pluggable feature, users can provide their own config loader implementation and configure it in config.yml. This allows their projects to have their own configuration loading methods.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pluggable config loading strategy](https://trello.com/c/I4RoFqbM/360-pluggable-config-loading-strategy)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pluggable config loading strategy](https://trello.com/c/aFkEvlB0/361-pluggable-config-loading-strategy)
