### ISSUE TITLE
ConsulRegistry will not be notified when pods go down to 0

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#573]
Consul registry will be notified when services that interested are changed, but will not be notified when pods go down to 0

**Comment by stevehu** [comment]
Does it mean the last pod shutdown won't unregister from the consul? Is this a bug?

**Comment by BalloonWen** [comment]
> Does it mean the last pod shutdown won't unregister from the consul? Is this a bug?

the last pod shutdown won't update light-4j ConsulRegistry, it's a light-4j bug.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ConsulRegistry will not be notified when pods go down to 0](https://trello.com/c/Jw7tWDQC/327-consulregistry-will-not-be-notified-when-pods-go-down-to-0)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ConsulRegistry will not be notified when pods go down to 0](https://trello.com/c/3wuPzU8T/328-consulregistry-will-not-be-notified-when-pods-go-down-to-0)
