### ISSUE TITLE
randomly pick up port number for dynamic registry

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#574]
The current logic to search for the next available port in a range defined in the server.yml is starting from the lowest number in the range. This is not ideal in some of the situations in a Kubernetes cluster. For example, if one service is down, the Kubernetes might start another service and light-4j going to allocate the same port on the same host. This cause a client to confuse that it still visits the old service but that one has already replaced by another service. This only happens if the previous service is killed without graceful shutdown and deregister from the Consul. The httpCheck use the serviceId in the endpoint as a path parameter and can mitigate the issue but not very user can use httpCheck for some reasons. It would be better for us to update the search logic for the next port to avoid reusing a port immediately. I am still trying to come up with a design and open to any suggestions.

**Comment by stevehu** [comment]
After discussing with @jiachen1120 and @BalloonWen, we think the best option is to use the random port within the range to start the server. This will significantly reduce the chance of conflict. In fact, on the same host, the chance service A crashes and service B starts to occupy the same part is already very slim. In a Kubernetes cluster, there is more chance that service A is down and service A is up in sequence.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [randomly pick up port number for dynamic registry](https://trello.com/c/zHGxkAzx/329-randomly-pick-up-port-number-for-dynamic-registry)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [randomly pick up port number for dynamic registry](https://trello.com/c/Umrh5o8J/330-randomly-pick-up-port-number-for-dynamic-registry)

**Comment by stevehu** [comment]
This issue is reopened as I found an issue during live testing. Unlike the previous implementation, we can check only (maxPort - minPort) times, we cannot use this number anymore as we are using a random number and there are chances that the same number might be pickup several times and some numbers are never been picked. Need to think about it more.

**Comment by ddobrin** [comment]
If the random port is tested and found busy, the random process gets followed repeatedly and will bring the number of iterations, as per the code from days ago.

A simple (although not elegant) version:
As this check happens at start-up, one could conceivably cache the "unsuccessful" binds in a set and try until the HashSet size equals (maxPort - minPort).
Hashset would right away be discarded after a bind is successful.

**Comment by stevehu** [comment]
@ddobrin Thanks for the suggestion. I will try this approach and test it out.

**Comment by NicholasAzar** [comment]
@stevehu would it be enough just to randomly pick the starting port between minPort & maxPort then loop over the rest in sequence (until you hit the starting port again)?

**Comment by stevehu** [comment]
@NicholasAzar I think that was the first solution we have implemented but we found some issues during the test and switched to a HashSet to track what has been bound.

**Comment by NicholasAzar** [comment]
The implementation in this commit https://github.com/networknt/light-4j/commit/1a2965fc86c57c6a8e3096101e9704ddfa168660 ? If so, I think that's different to what I mentioned in my above comment. Either way if the current solution is adequate then there's no benefit to revisit it.
