### ISSUE TITLE
-DskipTests doesn't work to skip unit tests

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#590]
maven build with parameter -DskipTests won't skip tests

**Comment by BalloonWen** [comment]
related maven issue: https://issues.apache.org/jira/browse/MNG-4979
based on the description, the -DskipTests set in command line won't overwrite the the <skipTests> since it was already set by <skip.unit.tests> property. This will make the implementation tricky, because if we won't to skip unit tests, but not integration-test, we set a flag  <skip.unit.tests>  to control this, but this will affect those projects already using "DsipTests".

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [-DskipTests doesn't work to skip unit tests](https://trello.com/c/PyDLM8Aw/400-dskiptests-doesnt-work-to-skip-unit-tests)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [-DskipTests doesn't work to skip unit tests 1.6.x](https://trello.com/c/YrQnSBXD/401-dskiptests-doesnt-work-to-skip-unit-tests-16x)
