### ISSUE TITLE
Implement rpc and websocket support with light-java-rpc

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#6]

**Comment by stevehu** [comment]
Until now, I am always thinking to implement websocket, rpc and graphql in the same code based but it look like they are not compatible at all. At this moment, I am seriously thinking to split the current light-java to spin off light-java-rest and then in the future to implement light-java-rpc with websocket support and light-java-graphql. All of them are based on some common libraries within light-java. Nothing has been done yet and I want to hear from you guys.

**Comment by dtchau** [comment]
Spinning off is a good idea. I think it'd be even better if light-java-rest/rpc/graphql are just collections of handlers. Anything light-java specific to connect the 2 (such as middlewares) can be part of an accompanying adapter project. 

Undertow users can likely benefit from your handlers. This can help improve your projects' profile, lead to more adoptation and encourage more contribution.

Just my 2 cents.

**Comment by stevehu** [comment]
Yes. This is the exact reason we have spin off light-java-rest and you can see there are only three handlers in light-java-rest. RPC is another beast and it would be a lot different.

**Comment by stevehu** [comment]
Websocket support is a built-in feature for light-4j and there are two examples in light-example-4j already. We now support JSON based RPC and other binary protocols will be supported upon requests.

https://github.com/networknt/light-example-4j/tree/master/websocket
