### ISSUE TITLE
Using JwtHelper on restful API for JWT security token config file issue

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#603]
Based on new design for the restful API, system will use openapi-security.yml as JWT security token configuration file. And new version light-codegen does not generate security.yml file for restful API anymore. 

In JwtVerifyHandler class, system check the openapi-security.yml  first, if not find, use security.yml for backward compatibility:

  // check if openapi-security.yml exist
  config = Config.getInstance().getJsonMapConfig(OPENAPI_SECURITY_CONFIG);
  // fallback to generic security.yml
 if(config == null) config = Config.getInstance().getJsonMapConfig(JwtHelper.SECURITY_CONFIG);

But in JwtHelper class, it only load security.yml for JWT config:

    public static final String SECURITY_CONFIG = "security";
    static Map<String, Object> securityConfig = (Map)Config.getInstance().getJsonMapConfig(SECURITY_CONFIG);
    static Map<String, Object> securityJwtConfig = (Map)securityConfig.get(JWT_CONFIG);

I think it should have same logic to check openapi-security.yml since resful API will use the file for configuration.

**Comment by stevehu** [comment]
@chenyan71 I double-checked the source code and you are right. In most cases, the default security.yml in the light-4j security module will be used for the JwtHelper. As JwtHelper is invoked from the JwtVerifyHandler in the openapi-security module in light-rest-4j, we need to find a way to pass the configuration to the JwtHelper; however, it is not an easy job as all the methods in the JwtHelper are static and the init code is a static block to load the security.yml. There is no knowledge for the JwtHelper to figure out who is the caller and which config file should be loaded (openapi-security vs. swagger-security). Do you have any good idea to get the issue fixed? Thanks for raising it up.

**Comment by stevehu** [comment]
To eliminate the dependency for security.yml config file, I have introduced a new class named JwtVerifier to replace the JwtHelper. The JwtHelper is still there but marked as deprecated. The following repositories must be changed as well for use the newly introduced class instead of using the static JwtHelper. 

light-rest-4j
light-hybrid-4j
light-graphql-4j
light-hybrid-4j
light-spa-4j
light-example-4j

**Comment by stevehu** [comment]
light-rest-4j https://github.com/networknt/light-rest-4j/issues/103

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [remove the dependency for security.yml for normal applications](https://trello.com/c/wwJpM9ZC/406-remove-the-dependency-for-securityyml-for-normal-applications)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [remove the dependency for security.yml for normal applications](https://trello.com/c/t5ZQarrl/407-remove-the-dependency-for-securityyml-for-normal-applications)
