### ISSUE TITLE
Collect Status and StackTrace on Error in light-4j handlers for auditing purposes

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#607]
Upon encountering an error, light-4j handlers log the error in log files.

For microservices where the developer wishes to audit the information in different types of persistent store, the status and stacktrace need to be collected from the light-4j handlers in the AUDIT_INFO, to allow the developer to access the information on demand.

The functionality should be disabled by default and can be enabled via the LightHttpHandlers' own configuration file, lighthttphandler.yml.

auditOnError: false
auditStackTrace: false

**Note:** The AUDIT_INFO should also be moved to the AttachmentConstants in the utility module, to avoid dependency of modules on the audit module, if this functionality is enabled

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Collect Status and StackTrace on Error in light-4j handlers for auditing purposes 1.6.x](https://trello.com/c/7TF3ymes/426-collect-status-and-stacktrace-on-error-in-light-4j-handlers-for-auditing-purposes-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Collect Status and StackTrace on Error in light-4j handlers for auditing purposes master](https://trello.com/c/SXS7PiXX/427-collect-status-and-stacktrace-on-error-in-light-4j-handlers-for-auditing-purposes-master)
