### ISSUE TITLE
BodyHandler double-conversion

### ISSUE THREAD

**Issue by trakkta** [networknt/light-4j#615]
Hi, I'm new to using this framework, so I'm not sure if I understand this correctly, but it seems the standard usage of BodyHandler (get the object JSON Map<> from the attachment) is susceptible to double-conversion in a typical scenario. It is customary to use specific DTOs for request data, not just Map<>, but to do that I'd need to invoke the objectMapper a second time to convert from Map<> to the specific DTO.

Thus, for my service I came up with a modified BodyHandler, that does nothing past the startBlocking() method:

`
package com.roku.entenghelloworld.handler;

import com.networknt.config.Config;
import com.networknt.handler.Handler;
import com.networknt.handler.MiddlewareHandler;
import com.networknt.utility.ModuleRegistry;
import com.roku.entenghelloworld.util.StringUtil;
import io.undertow.Handlers;
import io.undertow.server.HttpHandler;
import io.undertow.server.HttpServerExchange;
import io.undertow.util.Headers;

import java.util.List;

public class BodyHandler implements MiddlewareHandler {
    public void handleRequest(HttpServerExchange exchange) throws Exception {
        final String contentType = exchange.getRequestHeaders().getFirst(Headers.CONTENT_TYPE);

        if (!StringUtil.isNullOrEmpty(contentType)) {
            if (exchange.isInIoThread()) {
                exchange.dispatch(this);
                return;
            }

            exchange.startBlocking();
        }

        Handler.next(exchange, this.next);
    }

    //MiddlewareHandler
    public HttpHandler getNext() {
        return next;
    }

    public MiddlewareHandler setNext(HttpHandler next) {
        Handlers.handlerNotNull(next);
        this.next = next;
        return this;
    }

    public boolean isEnabled() {
        return config.isEnabled();
    }

    public void register() {
        ModuleRegistry.registerModule(this.getClass().getName(), Config.getInstance().getJsonMapConfigNoCache("body"), (List)null);
    }

    private volatile HttpHandler next;
}`

After I insert this body handler in the chain, inside my business handler all I have to do is:

`
package com.roku.entenghelloworld.handler.name;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.networknt.config.Config;
import com.networknt.handler.LightHttpHandler;
import com.networknt.service.SingletonServiceFactory;
import com.roku.entenghelloworld.model.NameUpdateRequest;
import com.roku.entenghelloworld.service.HelloWorldService;
import io.undertow.server.HttpServerExchange;
import io.undertow.util.StatusCodes;

public class PutHandler implements LightHttpHandler {
    public void handleRequest(HttpServerExchange exchange) throws Exception {

        helloWorldService.setName(objectMapper.readValue(exchange.getInputStream(), NameUpdateRequest.class));
        exchange.setStatusCode(StatusCodes.OK);
    }

    private static final ObjectMapper objectMapper = Config.getInstance().getMapper();
    HelloWorldService helloWorldService = SingletonServiceFactory.getBean(HelloWorldService.class);
}`

It seems a cleaner approach, and the double-conversion is gone. Maybe it'd be good to include this simpler version of the BodyHandler in the framework?

**Comment by stevehu** [comment]
The current body handler only convert the stream to map or list for json and a lot of users are using it in the business handler. Optionally, some users will convert the map or list into data object in the business handler which is a efficient process as map or list are in memory object. In fact, when using Jackson to convert stream to pojo, the first step is to convert to in memory map or list. There is an API in the Jackson to convert map or list to pojo.

**Comment by ddobrin** [comment]
This is what my client does and we have several dozen APIs in production.

In most cross-cutting concerns, they are using the map produced by the BodyHandler directly.

For a few complex update services, the developer chose to generate POJOs out of the map, as she felt that it serves her better in working on the validation and service execution logic.

**Comment by trakkta** [comment]
OK, makes sense. Is there any disadvantage of simply creating a DTO from the input stream directly as in my example? The reason I personally prefer DTOs is the better type safety, where I only need to worry about the correct value supplied by the client in the deserialization stage, and not in the business logic.

**Comment by ddobrin** [comment]
By any means, you can use them. 
My friend chose that for a large update request, and basically the only operation was a conversion: 
...
Object requestRoot = body.get(rootElementProperty);
...
MyDO apiDO = mapper.convertValue(requestRoot, new TypeReference<MyDO>() {});

... and the penalty, as it is in memory, is less <1ms, from her testing.

This kept the BodyHandler intact for the majority of the other endpoints of other APIs and it works well.
