### ISSUE TITLE
UT005001 Errors happen when sending metrics to influxDB

### ISSUE THREAD

**Issue by jsu216** [networknt/light-4j#616]
We notice that there are two types of errors happened when sending metrics to influxDB>

- NullPointerException: null

- IllegalStateException: UT000091: Buffer has already been freed

The first one happens more frequently.

After a couple of weeks investigation, we manage to locate the line of code that causes the errors. It’s the close outgoing connection. When Light4j tries to send metrics info to InfluxDB. because it creates a new connection every time, it needs to close it after sending the message. If comment out the line of closing connection, there would be no errors. We have tests to prove this conclusion.

This issue does not only happen to InfluxDB. It can happen anywhere when closing connection is required frequently.

The errors indicate some variables or resources have been freed. Since there is no impact to the functions, they should have been flagged as WARNING instead of ERROR to avoid confusion.

**Comment by stevehu** [comment]
@jsu216 I have seen the second error reported by some users and it seems that this f[ix](https://github.com/networknt/light-4j/pull/614) resolves it. For the metrics sending, we don't send the data constantly but in batch. So we create a new connection and then close it after the connection is used. I don't know the first error is thrown from Undertow or Light-4j, it is in the Undertow, we might not have a chance to change the logging level. Could you please attach a stacktrace for the error? Thanks a lot for the investigation.

**Comment by miklish** [comment]
Unless the class `Undertow` and the class `Xnio` are loaded by different class loaders, the lines 

`final Xnio xnio = Xnio.getInstance();`

and

`Xnio xnio = Xnio.getInstance(Undertow.class.getClassLoader());`

are actually identical.

**Comment by stevehu** [comment]
@miklish I totally agree with your analysis and that is why I don't understand why this change resolves the UT005001 issue reported by one of our users. In my mind, these errors make the user nervous but the functionality is not impacted as observed by @jsu216. I hope we can dig into the details and resolve them at a deeper level.

**Comment by jsu216** [comment]
@stevehu, the errors generated from undertow are in ERROR level. It would be hard to filter them simply by log levels. Some customized filters based on message content may be required if log filtering is an acceptable approach.
There open tickets in jboss/redhat regarding this "UT000091" error:
https://issues.jboss.org/browse/UNDERTOW-1359
https://access.redhat.com/solutions/4162841
