### ISSUE TITLE
data-source does not support two datasources (same type of database) with different password key

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#620]
Currently with light-4j data-source, user can define more that one data-source with different database types. For example: 

 com.networknt.db.SqlServerDataSource:
  - com.networknt.db.SqlServerDataSource:
    - java.lang.String: SqlServerDataSource
- com.networknt.db.OracleDataSource:
  - com.networknt.db.OracleDataSource:
    - java.lang.String: OracleDataSource

In the secret.yml, user can define different password for the datasource:

sqlServerPassword: ${secret.sqlServerPassword:change-me}
oraclePassword: ${secret.oraclePassword:password}

And user can have more than one data-source with same database type:

- com.networknt.db.MysqlDataSource:
  - com.networknt.db.MysqlDataSource:
    - java.lang.String: MysqlDataSource1
  - com.networknt.db.MysqlDataSource:
    - java.lang.String: MysqlDataSource2

But for this case, the 'MysqlDataSource1' and 'MysqlDataSource2' has different password, system cannot define it in the secret.yml file since the password key is pre-defined in the code.

    private static final String SQLSERVER_PASSWORD = "sqlServerPassword";

We may need change the code make the password key can be set from service.yml.

**Comment by stevehu** [comment]
With the latest changes in the config module, we don't need to use secret.yml for encrypted passwords anymore. If we put the passwords in the data-source.yml, do we still have this issue?

**Comment by chenyan71** [comment]
need change the datasource to get the password key from datasource config first:

**Comment by chenyan71** [comment]
String password = (String)mainParams.get(getDbPassKey());
        if (password==null) {
            password = (String)secret.get(getDbPassKey());
        }
        ds.setPassword(password);

**Comment by stevehu** [comment]
Should we just use `password` as the key?

**Comment by chenyan71** [comment]
I think that is a good point.   I will make the change

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [data-source does not support two data sources (same type of database) with a different password key 1.6.x](https://trello.com/c/Bu5n5mUm/477-data-source-does-not-support-two-data-sources-same-type-of-database-with-a-different-password-key-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [data-source does not support two data sources (same type of database) with a different password key master](https://trello.com/c/1Hux2ZEw/478-data-source-does-not-support-two-data-sources-same-type-of-database-with-a-different-password-key-master)
