### ISSUE TITLE
only display warning message for values.yml once

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#627]
When starting the server, the following message displayed several times. We need to find a way to display only once. 

```
Unable to load config 'values' with extension yml, yaml and json from external config, application config and module config. Please ignore this message if you are sure that your application is not using this config file.
```

**Comment by stevehu** [comment]
One way to eliminate the message is to create a dummy values.yml in the resources/config folder with only one default value. For example, `server.httpsPort: 8443`. However, this will prevent the message from displaying and users won't realize that this file should be overwritten. I haven't look at the code yet. but wondering if there is a way to display it only one. @jiachen1120 @BalloonWen What do you think?

**Comment by jiachen1120** [comment]
Hi! Maybe introduce a global flag to prevent loading values.yml block be triggered multiple time? I think this may be doable by just adding few lines.

**Comment by stevehu** [comment]
@jiachen1120 Could you please give it a try?

**Comment by jiachen1120** [comment]
@stevehu Sure! I am currently working on it :)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [only display warning message for values.yml once](https://trello.com/c/RagzicZb/501-only-display-warning-message-for-valuesyml-once)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [only display warning message for values.yml once master](https://trello.com/c/afksMAP1/502-only-display-warning-message-for-valuesyml-once-master)
