### ISSUE TITLE
make Http2Client.SSL private to block users to use it directly

### ISSUE THREAD

**Issue by miklish** [networknt/light-4j#629]
In light 1.6.11, the static variable Http2Client.SSL is no longer eagerly initialized. This is a functionally breaking change from light 1.6.10.

https://github.com/networknt/light-4j/pull/612/files#diff-905ed9c154545ecedeab300229fa9b99

Applications that assume the SSL variable is initialized, may fail mysteriously. I suggest that either:

1. Http2Client.SSL is deleted from Http2Client in light 1.6.12
2. Http2Client.SSL is deprecated

In either case, the changelog (and also possible deprecation comments) should contain documentation stating that SSL is no longer eagerly initialized, and that the Http2Client.getDefaultXnioSSL method should be used instead (https://github.com/networknt/light-4j/pull/624).

My team would personally like to see option 1. While it could cause build failures in user applications, we believe that this is an appropriate result, as it will force end users to examine their use of the SSL variable and save them having their code build, but then fail mysteriously when run.

**Comment by stevehu** [comment]
@miklish It can be removed. For normal applications, they are using the connect method of Http2Client so nobody realized that the SSL is lazily initialized. In my mind, it won't break existing applications. The only application that is impacted is the light-router which is using the Http2Client.SSL for the Undertow Client used in the router. It was a hack in my mind and the risk is controlled.

**Comment by miklish** [comment]
Ok cool. I will create a PR to make it private. Thanks

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [make Http2Client.SSL private to block users to use it directly](https://trello.com/c/QTI0tp3t/508-make-http2clientssl-private-to-block-users-to-use-it-directly)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [make Http2Client.SSL private to block users to use it directly master](https://trello.com/c/ZgasTnTH/509-make-http2clientssl-private-to-block-users-to-use-it-directly-master)
