### ISSUE TITLE
add JVM Metrics to metrics module for  InfluxDb

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#639]
add JVM Metrics to metrics module for  InfluxDb

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add JVM Metrics to metrics module for InfluxDb 1.6.x](https://trello.com/c/4Kt6tLW5/531-add-jvm-metrics-to-metrics-module-for-influxdb-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add JVM Metrics to metrics module for InfluxDb master](https://trello.com/c/Elxx6Io9/532-add-jvm-metrics-to-metrics-module-for-influxdb-master)
