### ISSUE TITLE
Service registration fails with Consul >1.7.x

### ISSUE THREAD

**Issue by Relivian** [networknt/light-4j#647]
This issue was tested with OAuth2 services. Consul versions before 1.7 work fine.
To get specific messages from the OAuth2 services about what went wrong the consul configuration (consul.yml) had to contain Consul's IP address instead of the host name.
[consul.txt](https://github.com/networknt/light-4j/files/4195529/consul.txt)

**Comment by stevehu** [comment]
The root cause due to the following change. 

https://github.com/hashicorp/consul/pull/6874

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Service registration fails with the latest Consul master](https://trello.com/c/k6iHADo1/569-service-registration-fails-with-the-latest-consul-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Service registration fails with the latest Consul 1.6.x](https://trello.com/c/1HKNU6l8/570-service-registration-fails-with-the-latest-consul-16x)
