### ISSUE TITLE
Service discovery failure at beginning of service startup 

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#649]
Scenario:
when default consul config:  enableHttp2=false
In the service API, the service method need call multiple downstream service API.
At   beginning of service startup, some API Service discovery from consul by service Id will failed, and after for while, the become success with no error.

Code:
It looks like thread issue. in ConsulRegistry, for some serviceName:

      urls = serviceCache.get(serviceName);

The urls return empty list. It means the thread load the service with empty url value from consul discovery.

Changed the consul config to enableHttp2=true. The issue disappear.

**Comment by chenyan71** [comment]
It happened only when use https connect to consul. It works for http consul connection

**Comment by stevehu** [comment]
I think this is the same issue. https://github.com/networknt/light-4j/issues/634

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Service discovery failure at beginning of service startup 1.6.x](https://trello.com/c/DtZo6n9W/573-service-discovery-failure-at-beginning-of-service-startup-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Service discovery failure at beginning of service startup master](https://trello.com/c/oZlAJfZW/574-service-discovery-failure-at-beginning-of-service-startup-master)
