### ISSUE TITLE
LightHttpClient Drops the inflight connections when TTL expires

### ISSUE THREAD

**Issue by kumasath** [networknt/light-4j#650]
Hi Steve,
In Light HttpClient connection (http2 protocol) when the TTL expires the existing inflight connection is reset and inturn it causes few of the inflight transactions to fail.

**Light4j version:  1.5.21**

**Code Reference:**
CacheableConnection.java > isOpen() checks if current time is greater than (lifeStartTime + ttl) and closes the connection if true. When closing, it does not check if there are any in-flight requests associated with the connection.
This results in in-flight requests getting dropped.

**Comment by stevehu** [comment]
The issue is related to the light-consumer-4j and I will close this one and open another in that repo.
