### ISSUE TITLE
Upload problem

### ISSUE THREAD

**Issue by xiangshibo** [networknt/light-4j#660]
When I upload the file, the contentType is multipart / form-data. Something went wrong. The reason is that when the convert method in the BodyConverter class gets the parameter value, the file type is according to String. Is this a bug or am I using it the wrong way.
![image](https://user-images.githubusercontent.com/11767971/75681178-08455000-5cce-11ea-8d84-c4e7dd3faed4.png)

**Comment by stevehu** [comment]
This is not a bug. The default BodyHandler only works with JSON and Form. If you want to handle file upload, you need to provide your own handler according to the format or encoder you have for the data.

**Comment by stevehu** [comment]
Here is an example of how to upload pdf files. 

https://github.com/networknt/light-example-4j/blob/1.6.x/client/pdf/src/main/java/com/networknt/example/pdf/handler/PdfReportGetHandler.java

**Comment by stevehu** [comment]
Another example of upload  https://www.codota.com/code/java/methods/io.undertow.util.Headers/extractQuotedValueFromHeader

**Comment by xiangshibo** [comment]
I override the methods in BodyHandler and redefined the processing link. The problem was resolved. Thank you very much for your help.

**Comment by stevehu** [comment]
I am so glad it helps. Happy coding :)
