### ISSUE TITLE
 Transaction management

### ISSUE THREAD

**Issue by xiangshibo** [networknt/light-4j#661]
How do you manage transaction for each service in the framework? Are there any examples ？Thank you.

**Comment by stevehu** [comment]
There are two areas that we need to cover. How to connect to two different databases from one service and ensure consistency. Take a look at this lib https://www.atomikos.com/Main/TransactionsEssentials

For distributed transactions between services, light-eventuate-4j and light-saga-4j are designed for it. 

https://doc.networknt.com/architecture/transaction/
