### ISSUE TITLE
Compared to WSO2 and Kong

### ISSUE THREAD

**Issue by raviada** [networknt/light-4j#662]
Hello guys, thanks for well documented framework and for all the tools in place to get this framework work together. 
I have a higher level question regarding choosing a framework for our microservice deployment. I have a lot of experience working with WSO2 API gateway and Identity manager for gateway and user provisioning. It works most part but it is a monolithic servlet engine but they support distributed deployment of different modules in Kubernetes etc. It is complex in understanding different configurations and hard to deploy to make it to work in a cohesive way.

My question is how LIGHT framework is compared to other frameworks/applications such as WSO2 and Kong etc in the java world?

**Comment by stevehu** [comment]
The light platform is an ecosystem that has its light-oauth2 for authentication and authorization. Light-router and light-proxy for API gateway and service mesh. Everything is microservices just like lego blocks. Users can pick up services they need to form their applications. Unlike other gateway providers, we have frameworks to build applications and each application can embed a gateway to address all the cross-cutting concerns. 

The goal for us is the highest throughput, the lowest latency, and the smallest memory footprint to save the production cost especially when deployed to the cloud. 

Let us know if you have any specific questions. Thanks for considering light-4j and happy coding.

**Comment by stevehu** [comment]
BTW, most Java frameworks are still based on Java EE which was designed almost two decades ago. Multi-core CPUs were not popular and software vendors like Sun and IBM wanted to sell more Spark and RISC machines to generate more revenues. The one thread per request is killing Java EE and waste CPU resources significantly. Even though some claim that they have frameworks designed as cloud-native, they are still Java EE. What is the point to use a light-weight Docker container if you have a heavy-weight Servlet container already. Take a look at this the performance difference for the Micronaut. 

https://github.com/networknt/microservices-framework-benchmark/pull/63

Kong is very slow as we have tested. It can support only thousands of requests per second and very hard to add new features in the architecture. Take a look at light-router, you can put any middleware handlers to the request/response chain through configurations and it is lighting fast.

**Comment by raviada** [comment]
Great, thank you for quick response. I will checkout oauth2, router and proxy modules. 
Is OAuth2 setup to verify new accounts created (like user registers an account and wait for account verification through code sent in the email). Until users verify the account, we should not be able to access any services (any other routes from SPA app for example). Do we have to code this specifically or offered out of the box?

**Comment by stevehu** [comment]
Take a look at this tutorial. https://doc.networknt.com/tutorial/open-banking/
