### ISSUE TITLE
set connection expire time client.yml file and get error on service start

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#677]
The default http2 connection expire time set in client module is 1000,000 seconds:
   public static final long DEFAULT_CONNECTION_EXPIRE_TIME = 1000000;
When we try to set the value in client.yml to have longer time for connection and got error>

Client.yml:
request:
  errorThreshold: 2
  timeout: 3000
  resetTimeout: 7000
  connectionExpireSize: 2000000  

Error: 
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [set connection expire time client.yml file and get error on service start 1.6.x](https://trello.com/c/IxVsijRf/621-set-connection-expire-time-clientyml-file-and-get-error-on-service-start-16x)
