### ISSUE TITLE
connection expired close issue when inflight request still running

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#679]
Current httpsconnection pool will close the connection when the connection opened more that expire time setting:

            if (System.currentTimeMillis() - lifeStartTime >= expireTime || (requestCount.get() >= maxReqCount && maxReqCount != -1)) {
                    this.clientConnection.close();
           }
But maybe other threads are using the connection. So need park the connection for a while. then close the connection.

Light-consumer-4j had similar issue and fixed there:
https://github.com/networknt/light-consumer-4j/pull/45

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [connection expired close issue when inflight request still running 1.6.x](https://trello.com/c/yaIeXdkG/624-connection-expired-close-issue-when-inflight-request-still-running-16x)
