### ISSUE TITLE
Audit logging

### ISSUE THREAD

**Issue by raviada** [networknt/light-4j#702]
I am making really good progress with light4j. Thank you for putting the good work.

I have a need for storing all CRUD transactions per user in a database for audit purposes to know who and what changed at any give point of time. What is the best way to accomplish this? Is it better to write a custom audit handler or any recommended way to address this?

**Comment by stevehu** [comment]
@raviada I am glad you figure it out on your own. It is a pretty complicated system as it is designed for enterprises. To audit CRUD in a database, you can create your AuditHandler and replace the default one in the request/response chain. One of the banks is doing that. There are a lot of tricky performance tuning considerations I remember. @ddobrin is the best guy to ask specific questions as he did it. I would be so happy if you could open source your handler once it is done.

**Comment by ddobrin** [comment]
@raviada - due to some other commitments, I could not follow a number of projects. If this is still an issue you are interested in addressing, just drop a comment here. thank you
