### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by raviada** [networknt/light-4j#706]
What is the best way to build and run docker images for light4j rest apis? I see that a Dockerfile is generated from codegen. When I build the image and run it I get this error.
```
Error: Could not find or load main class com.networknt.server.Server
Caused by: java.lang.ClassNotFoundException: com.networknt.server.Server
```

I am using the following command to build and run the image.
```
docker build -t catalog:1.0.2 -f docker/Dockerfile .
docker run catalog:1.0.2
```

Are we adding all the pom dependencies when building a `fatjar`?

**Comment by stevehu** [comment]
We also generate build.sh to create docker images and publish them to the docker hub. Modify it based on your docker hub account or internal artifact repository. 

To build fatjar, you need to use -Prelease as we don't want to generate farjar during the development.
