### ISSUE TITLE
JwtVerifier throw NullPointerException if user remove the jwtr/certificate from openapi-security.yml

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#709]
In the openapi-security.yml (start from ligh-codegen), light-4j define default certificate for jwt token:

jwt:
  certificate:
    '100': primary.crt
    '101': secondary.crt

If the jwt token key is not in the config list (by default: 100/101), system will go to key server to retrieve certificate (client.yml). 

But in some case, user may not want to define default certificate and try to remove it from openapi-security.yml, then service API get error on service startup:

Caused by: java.lang.NullPointerException
         at com.networknt.security.JwtVerifier.<init>(JwtVerifier.java:120)
         at com.networknt.openapi.JwtVerifyHandler.<clinit>(JwtVerifyHandler.java:79)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JwtVerifier throw NullPointerException if user remove the jwtr/certificate from openapi-security.yml](https://trello.com/c/DYm1XjzT/662-jwtverifier-throw-nullpointerexception-if-user-remove-the-jwtr-certificate-from-openapi-securityyml)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JwtVerifier throw NullPointerException if user remove the jwtr/certificate from openapi-security.yml master](https://trello.com/c/uoNBcc9y/663-jwtverifier-throw-nullpointerexception-if-user-remove-the-jwtr-certificate-from-openapi-securityyml-master)

**Comment by stevehu** [comment]
@chenyan71 Thanks a lot for the fix. I am building snapshot versions for both 1.6.x and 2.0.x now. It should be ready within one hour.
