### ISSUE TITLE
client module support Multipart request body

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#710]
Current light-4j http2Client module doesn't support Multipart request body.
And the request body is processed by StringWriteChannelListener which is string base only.

Undertow client ClientRequest support add attachment with request body. But  the service API maybe need call other service which need Multipart in request body, for example:

pdf name and meta data in one part of request body with Json format 
pdf content as byteArray in another part of the request body.

We probably can refer to apache http client:

https://hc.apache.org/httpcomponents-client-ga/httpmime/apidocs/org/apache/http/entity/mime/MultipartEntityBuilder.html

**Comment by chenyan71** [comment]
In the current client module, it support the binary response (image, pdf ...) in the response attachment by byteBufferClientCallback (issue #625) .

 But it may need add support for request body with binary as well (multipart-requests)

https://swagger.io/docs/specification/describing-request-body/multipart-requests/

requestBody:
  content: 
    multipart/form-data: # Media type
      schema:            # Request payload
        type: object
        properties:      # Request parts
          id:            # Part 1 (string value)
            type: string
            format: uuid
          address:       # Part2 (object)
            type: object
            properties:
              street:
                type: string
              city:
                type: string
          profileImage:  # Part 3 (an image)
            type: string
            format: binary

Currently ClientCallback read request by String format only (StringWriteChannelListener). It should have option to read as byte array.

**Comment by stevehu** [comment]
@chenyan71 Yes. We need to support the binary request body. The problem we had before is that we need to ensure that both client and server need to understand the format of the body in order to parse it gracefully. The swagger multipart-requests is a great example that we can implement so that the server has some information to parse the body. The only problem we have is that the body-parser today doesn't have the knowledge of the specification yet. Do you have any suggestions for the implementation?

**Comment by chenyan71** [comment]
@stevehu I don't think framework need know the specification definition. It is between server and client.
For example, the spec define the request need file name and pdf body, the client request need wrap the two fields and add needed header attributes based on the spec. Server side will parse request body based on the spec which it defined.  
The problem is current client module only support String as request body

**Comment by stevehu** [comment]
@chenyan71 I have migrated your pdf client demo application from 1.6.x branch to master at https://github.com/networknt/light-example-4j/tree/master/client/pdf

I tried all the test cases and they work very well. My understanding is to move the logic to the light-4j. Am I missing something?

**Comment by chenyan71** [comment]
Yes, will move the some implementation to light-4j.
The sample provided the reference for Multipart request handling by using HashMap:

   HashMap<String, Object> requestMap = new HashMap<>();
   requestMap.put("name", "test_sample.pdf");
   requestMap.put("profileFile", IOUtils.toByteArray(resourceAsStream));
 connection.sendRequest(request, createClientCallback(reference, latch,ByteBuffer.wrap(SerializationUtils.serialize(requestMap))));

But user can define their request object instead of Map if needed

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [client module support Multipart request body light-4j master](https://trello.com/c/8kgVYiPj/721-client-module-support-multipart-request-body-light-4j-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [client module support Multipart request body light-4j 1.6.x](https://trello.com/c/qtyeqJuA/722-client-module-support-multipart-request-body-light-4j-16x)
