### ISSUE TITLE
Token replacement in config files does not allow special characters

### ISSUE THREAD

**Issue by tsuilouis** [networknt/light-4j#723]
@chenyan71 and I have noticed that there is some non-obvious behaviour when config values are parsed in yaml files. Basically, it looks like the backslash '\\' and dollar sign '$' are not parsed as ordinary characters when placed in config files.

We've noticed this happen before in SQL Server queries that involve JSON-related functions as they use a dollar sign to reference the root object. We had two workarounds:

For a top-level entry, we escaped the dollar sign (\\$). E.g. `xyz.query: SELECT JSON_VALUE(abc, '\$.foo.bar') FROM def`

We also placed queries as elements in a list so that we didn't have to escape the dollar sign. E.g. 

```
xyz.queryMap:
   query1: SELECT JSON_VALUE(abc, '$.foo.bar') FROM def;
   query2: SELECT JSON_QUERY(abc, '$.foo.baz') FROM def;
```

We also had this recently happen for a `metrics.influxdbPass` value for which the encrypted password contained a dollar sign. From the stacktrace we saw, the error occurs at https://github.com/networknt/light-4j/blob/e56e0cf9c235c09bd1b7a6659c2cd31777f17f9f/config/src/main/java/com/networknt/config/ConfigInjection.java#L73.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Token replacement in config files does not allow special characters light-4j master](https://trello.com/c/mgKcYsCj/723-token-replacement-in-config-files-does-not-allow-special-characters-light-4j-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Token replacement in config files does not allow special characters light-4j 1.6.x](https://trello.com/c/9ZUlpHu4/724-token-replacement-in-config-files-does-not-allow-special-characters-light-4j-16x)
