### ISSUE TITLE
set serviceMap for lightCluster after first time service discovery

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#730]
In the LightCluster, it will try to get the service urls by service Id from serviceMap cache

        List<URL> urls = serviceMap.get(serviceId);

If it is not existing, go to consulRegistry to do service discovery.

But the discovery result should be set to serviceMap cache.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [set serviceMap for lightCluster after first time service discovery light-4j master](https://trello.com/c/OCfS5UCQ/709-set-servicemap-for-lightcluster-after-first-time-service-discovery-light-4j-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [set serviceMap for lightCluster after first time service discovery light-4j 1.6.x](https://trello.com/c/nndobzJE/710-set-servicemap-for-lightcluster-after-first-time-service-discovery-light-4j-16x)
