### ISSUE TITLE
Add  Multipart request body & Multipart response support

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#742]
Currently client module can support Multipart request body & Multipart response by wrap it to map. We have sample in light-example-4j:

https://github.com/networknt/light-example-4j/tree/1.6.x/client/pdf

But for convenient, we probably should add an client object and builder class for consumer.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Multipart request body & Multipart response support light-4j 1.6.x](https://trello.com/c/iswW03IM/751-add-multipart-request-body-multipart-response-support-light-4j-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Multipart request body & Multipart response support light-4j master](https://trello.com/c/dgcItBSs/752-add-multipart-request-body-multipart-response-support-light-4j-master)
