### ISSUE TITLE
Handle the limit file size for upload/download

### ISSUE THREAD

**Issue by PeterKieu** [networknt/light-4j#743]
The missing option for handling the limit file size for upload/download to protect exception on memory overload/overflow.
Please update to this:
1. server.yml 
#this limit upload/download file size
maxTransferFileSize: 1000000
2. Project: https://github.com/networknt/light-4j/tree/master/server
- Class ServerConfig.java
    int maxTransferFileSize;
- Class Server.java   
  .setServerOption(UndertowOptions.MAX_ENTITY_SIZE, serverConfig.getMaxTransferFileSize())
     .setServerOption(UndertowOptions.MULTIPART_MAX_ENTITY_SIZE, 10*serverConfig.getMaxTransferFileSize())

**Comment by stevehu** [comment]
To make it backward compatible, I have added it to the ServerOption to set the default value if it doesn't exist in the server.yml like other seldom-used options. Thanks a lot for the code you put into the issue. I should have asked you to submit a PR :) The credit goes to you, my friend.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handle the limit file size for upload/download light-4j  master](https://trello.com/c/Uj33rLPQ/740-handle-the-limit-file-size-for-upload-download-light-4j-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Multipart request body & Multipart response support light-4j master](https://trello.com/c/dgcItBSs/752-add-multipart-request-body-multipart-response-support-light-4j-master)
