### ISSUE TITLE
Valuemap not pickup the values loaded from config server.

### ISSUE THREAD

**Issue by jsu216** [networknt/light-4j#744]
https://github.com/networknt/light-4j/blob/3e10d4c63cba4e3f01719be49158c735616b64b8/config/src/main/java/com/networknt/config/ConfigInjection.java#L53

When ConfigInjection is loaded, the `valueMap `is null or only has values in local config files. After loading from config server, the `valueMap `is not udpated with the values from config server and causing ConfigException thrown.

**Comment by miklish** [comment]
@jsu216 Hi John...

1) What caused this issue?

2) Is this the only issue? Is it possible that the operation of the Config class is affected in other ways?

**Comment by jsu216** [comment]
In a previous [commit](https://github.com/networknt/light-4j/commit/2a10b3cd58b61dbdb43d679d696e8d780383f8fa), the line #53 was moved from the `getValue` method to a static field. This caused the valueMap not updated after values loaded from config server.
I don't see any issue after move it back because the reason it was moved out was just to "prevent multiple warning" message.

**Comment by miklish** [comment]
@jsu216 Thank you!

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Valuemap not pickup the values loaded from config server light-4j 1.6.x](https://trello.com/c/15Ilgrju/738-valuemap-not-pickup-the-values-loaded-from-config-server-light-4j-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Valuemap not pickup the values loaded from config server light-4j master](https://trello.com/c/xe6XIpRg/739-valuemap-not-pickup-the-values-loaded-from-config-server-light-4j-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handle the limit file size for upload/download light-4j  master](https://trello.com/c/Uj33rLPQ/740-handle-the-limit-file-size-for-upload-download-light-4j-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [update config.yml in testing for typos light-codegen 1.6.x](https://trello.com/c/7XQDXtyL/742-update-configyml-in-testing-for-typos-light-codegen-16x)
