### ISSUE TITLE
Ability to have control over typecasting when injecting environment variables into configuration

### ISSUE THREAD

**Issue by yunusual** [networknt/light-4j#767]
I'm injecting the first 7 digits of the Git commit hash to my application with the use of an environment variable to keep track of versions and releases.

Example environment variable: `GIT_HASH=2312e58`.

This gets injected into a parameter in my config.yml file: `gitHash: ${GIT_HASH:NOT_DEFINED}`

My desire is to always have this value injected as a String, but depending on its value, the type casting logic injects this variable in different types. Some examples:
- GIT_HASH=a457b37 (Injected as a String)
- GIT_HASH=2312e58 (Injected as a Double - Interpreted as a decimal number in scientific notation, i.e. 2.312E61)
- GIT_HASH=9975371 (Injected as an Integer)

This creates an issue for the application since it needs this value as a plain String and it's cumbersome to convert it back to a String, especially in case of a Double.

Could it be an option to provide an optional type parameter in the pattern for injections? Or alternatively, some indicator to completely skip type casting for a specific parameter and always inject it as a String.

### Current workaround:
A static prefix is added to the environment variable, e.g. `GIT_HASH=HASH_2312e58` so that the type casting always evaluates it as a String. The application strips off `HASH_` prefix later when the configuration is used.

**Comment by stevehu** [comment]
Trying to dig into the code and it looks like there is no easy solution to resolve it. To add the type info to the template will make the configuration file so messy. In my opinion, your current workaround makes sense and it might be the best solution for this very special use case. Let's leave it as it is and reopen it if more use cases come up. Thanks a lot for raising it.
