### ISSUE TITLE
Register JavaTimeModule for the default Jackson ObjectMapper from Config

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#82]
As light-codegen is using Java 8 DateTime in generated models(POJOs), it would be convenient to have the default ObjectMapper from Config to support serialization of DateTime in JSON. 

```
    static void setupMapper(ObjectMapper mapper) {
        mapper.registerModule(new JavaTimeModule());
        mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
    }

pom dependency:
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${version.jackson}</version>
        </dependency>
```

**Comment by pragmaticway** [comment]
The code change and test cases looks good! I'd add one more test case for LocalDateTime as well in addition to ZonedDateTime.

**Comment by stevehu** [comment]
@pragmaticway Could you please submit a pull request for the additional test case on develop branch? Thanks.

**Comment by stevehu** [comment]
Pull Request is merged. Thanks @pragmaticway for your help. 

https://github.com/networknt/light-4j/pull/83
