### ISSUE TITLE
Error status resulted at framework middleware handler is missing in auditInfo

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#839]
Currently, Error status resulted at framework middleware handler is missing in auditInfo. The reason of it would be that the response sending may be completed before adding the status into auditInfo. Therefore, the ExchangeCompleteListener inside the audit handler may not be able to add the error status into the auditMap. 

We may need to adjust te order of codes within LightHttpHandler.setExchangeStatus() method from
```java
default void setExchangeStatus(HttpServerExchange exchange, Status status) {
        ...
        exchange.getResponseSender().send(status.toString()); 
        ...
        Map<String, Object> auditInfo = exchange.getAttachment(AttachmentConstants.AUDIT_INFO);
        if(auditInfo == null) {
            auditInfo = new HashMap<>();
            exchange.putAttachment(AttachmentConstants.AUDIT_INFO, auditInfo); 
        }

        // save info for auditing purposes in case of an error
        if(auditOnError)
            auditInfo.put(Constants.STATUS, status);
        if(auditStackTrace) {
            auditInfo.put(Constants.STACK_TRACE, Arrays.toString(elements));
        }
    }
```
to 

```java
default void setExchangeStatus(HttpServerExchange exchange, Status status) {
        ...
        Map<String, Object> auditInfo = exchange.getAttachment(AttachmentConstants.AUDIT_INFO);
        if(auditInfo == null) {
            auditInfo = new HashMap<>();
            exchange.putAttachment(AttachmentConstants.AUDIT_INFO, auditInfo); 
        }

        // save info for auditing purposes in case of an error
        if(auditOnError)
            auditInfo.put(Constants.STATUS, status);
        if(auditStackTrace) {
            auditInfo.put(Constants.STACK_TRACE, Arrays.toString(elements));
        }
        exchange.getResponseSender().send(status.toString()); 
    }
```
To send the response after setting error status.

**Comment by stevehu** [comment]
@jiachen1120 Good catch!!! This makes perfect sense. Could submit a PR to get it fixed? Thanks.

**Comment by jiachen1120** [comment]
@stevehu Sure. Will submit a PR!

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error status resulted at framework middleware handler is missing in auditInfo light-4j 1.6.x](https://trello.com/c/2DLlOWxp/868-error-status-resulted-at-framework-middleware-handler-is-missing-in-auditinfo-light-4j-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error status resulted at framework middleware handler is missing in auditInfo light-4j master](https://trello.com/c/4zrOz8Pp/869-error-status-resulted-at-framework-middleware-handler-is-missing-in-auditinfo-light-4j-master)
