### ISSUE TITLE
AuditHandler cannot logged request, response, query parameters if response is sent by a framework middleware handler 

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#840]
The current design of the audit handler is that users implement their own way to audit their requests and response in their own handler. 

However, it seems if the response is sent by framework middleware handler, people may be hard to auditing the request and response. For example, if openapi validation error happen, status will be sent back but this response won't be auditted.

Probably we can provide a option to users to audit these kind of request and response.

There are two situation:
1. Framework help users auditting every request and response, regardless of success or fail

- User can enable dump handler at this time. We can retrieve dumpped request and response from dumpped exchange attachment and add them into auditMap

2. Framework help users auditting failed request and response, and the response is sent by a framework middleware handler

- User set the auditOnError to true, then the response at this moment is the error status, which already exists in the auditInfo, we can directly add it to the auditMap

**Comment by stevehu** [comment]
@jiachen1120 I would prefer the second option and still position the dump handler as a debugging tool for the dev environment as it is too heavy. @miklish What do you think?

**Comment by jiachen1120** [comment]
@stevehu Yeah. Acctually the second situation already can fulfill our customer's requirements. Just wondering will it be useful if we also added dumpped request and response into auditMap in dev environment when people enable dumpped handler for debugging?

I personally think option2 should be enough. @miklish Looking forward to your opinion.

**Comment by miklish** [comment]
I prefer option 2 as well @stevehu @jiachen1120

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AuditHandler cannot logged request, response, query parameters if response is sent by a framework middleware handler light-4j 1.6.x](https://trello.com/c/ASKPTCjB/879-audithandler-cannot-logged-request-response-query-parameters-if-response-is-sent-by-a-framework-middleware-handler-light-4j-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AuditHandler cannot logged request, response, query parameters if response is sent by a framework middleware handler light-4j master](https://trello.com/c/bL4CvGcL/880-audithandler-cannot-logged-request-response-query-parameters-if-response-is-sent-by-a-framework-middleware-handler-light-4j-mast)
