### ISSUE TITLE
Users want to customize status response when schema validation fails

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#841]
When schame validation fails, the framework will directly return the error status object {"statusCode":400 ...}. However, one of our user want to add their own information into this status response.

A generic way to implement it is to provide users a status wrapper interface and let user costomize their own Status and them inject the customized status into framework through SingletonFactory

example:
```java
interface IStatusFactory {
    Status wrap(Status status, HttpServerExchange exchange);
}
```

User implement the IStatusFactory and configure service.yml

```java
public class ECIFStatusFactory implements IStatusFactory {
   @Override
    public Status wrap(Status, HttpServerExchange exchange) {
        return ECIFStatus(status, exchange);
    }
}

public class ECIFStatus extends Status {
...
}
```

```yml
singletons:
    - com.networknt.status.IStatusFactory
        - com.networknt.petstore.model.ECIFStatusFactory
```

Within LightHttpHandler.setExchangeStatus() method:
```java
default void setExchangeStatus(HttpServerExchange exchange, Status status) {
        // wrapping status into customized status (ECIFStatus)
        status = statusFactory == null ? status : statusFactory.wrap(status, exchange);
        ...
        exchange.getResponseSender().send(status.toString());
        ...
    }
```

Looking forward to your opinion. Thanks

**Comment by stevehu** [comment]
@jiachen1120 This is a good approach to customize the error message. To extend the concept of error message customization, one organization is asking if we can hide the detail of the status response to only the response code and error code for north-south traffic and keep the entire status response for east-west traffic. There is a security concern to send the full status object to the client coming from the Internet. If the Internet user receives the error, they don't know what is going on and they have to report to the API owner who can search the runbook to find the full text of descriptions as well as the resolutions in different scenarios.

**Comment by jiachen1120** [comment]
@stevehu  Thanks Steve. We also believe that it is good to provide users with customized error message. Therefore, can we make a pull request for this?

**Comment by stevehu** [comment]
Yes. Please.

**Comment by miklish** [comment]
@jiachen1120  One suggestion... The "I" in IStatusFactory does not align with the naming conventions in light-4j... I would suggest renaming this interface to simply StatusFactory... @stevehu what do you think?

**Comment by stevehu** [comment]
@jiachen1120 I think @miklish is right. It is seldom for us to use I as a prefix these days as the modern IDE has a clear indicator on which file is a class and which one is an interface. The prefix will make the interface name not a valid word and causing some warnings in some IDEs. The practice was pretty popular in the old days that IDE doesn't have any indication on the class type. Thanks.

**Comment by jiachen1120** [comment]
@miklish @stevehu I see, will change it. Thanks for the explaination!

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users want to customize status response when schema validation fails light-4j 1.6.x](https://trello.com/c/aSYGdLev/888-users-want-to-customize-status-response-when-schema-validation-fails-light-4j-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users want to customize status response when schema validation fails light-4j master](https://trello.com/c/fxqT3cR3/889-users-want-to-customize-status-response-when-schema-validation-fails-light-4j-master)
