### ISSUE TITLE
Enhance the audit handler to take the timestamp pattern as parameter.

### ISSUE THREAD

**Issue by jaswalkiranavtar** [networknt/light-4j#858]
Right now, the audit handler writes timestamp in epoch time format.

 {"timestamp":1606942812176, "client_id":"0oa600nb7nurIk8fT1d6", "user_id":null, "scope_client_id":null, "endpoint":"/pets/{petId}@get", "serviceId":null,"request":null,"response":null, "X-Correlation-Id":"VT_PyMsNR_WYhvqn6a4ZXQ", "X-Traceability-Id":"LZIaEFAipVQvSTTEz", "statusCode":200, "responseTime":2}

We want timestamp in this format and want to expose a parametere when user can specify this pattern in logback or audit.yml:
yyyy-MM-dd'T'HH:mm:ss.SSSZ

**Comment by stevehu** [comment]
The pattern has to be in the audit.yml.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enhance the audit handler to take the timestamp pattern as parameter. light-4j master](https://trello.com/c/MtrNMqLZ/886-enhance-the-audit-handler-to-take-the-timestamp-pattern-as-parameter-light-4j-master)
