### ISSUE TITLE
bug when auditing service id

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#861]
There's an error in current audit handler
class com.networknt.server.ServerConfig cannot be cast to class java.util.Map (com.networknt.server.ServerConfig is in unnamed module of loader 'app'; java.util.Map is in module java.base of loader 'bootstrap')
	at com.networknt.config.Config$FileConfigImpl.getJsonMapConfig(Config.java:301)
	at com.networknt.config.Config$FileConfigImpl.getJsonMapConfig(Config.java:343)
	at com.networknt.audit.AuditHandler.auditServiceId(AuditHandler.java:285)
	at com.networknt.audit.AuditHandler.handleRequest(AuditHandler.java:127)

this happens when getting server's config

**Comment by stevehu** [comment]
I think I had encountered the same issue before. This is due to the config cache in the same process with ServerConfig object already. If we want to load the config in a map, we need to use NoCache. Take a look at this line of the code to get it fixed. 

https://github.com/networknt/light-4j/blob/master/client/src/main/java/com/networknt/client/Http2Client.java#L131

**Comment by BalloonWen** [comment]
> I think I had encountered the same issue before. This is due to the config cache in the same process with ServerConfig object already. If we want to load the config in a map, we need to use NoCache. Take a look at this line of the code to get it fixed.
> 
> https://github.com/networknt/light-4j/blob/master/client/src/main/java/com/networknt/client/Http2Client.java#L131

yes, I made the code change and tested, but was facing some unrelated build issue, will create a PR once fix the build issue.

**Comment by stevehu** [comment]
The test case issue with portal-registry and consul has been fixed already and the master branch is clean. You can try that again. Thanks.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bug when auditing service id light-4j master](https://trello.com/c/8AGoOLmm/884-bug-when-auditing-service-id-light-4j-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bug when auditing service id light-4j 1.6.x](https://trello.com/c/gdVYRArt/885-bug-when-auditing-service-id-light-4j-16x)
