### ISSUE TITLE
Split the error log in LightHttpHandler interface into 2 seperate error log statements

### ISSUE THREAD

**Issue by jaswalkiranavtar** [networknt/light-4j#864]
If there is any error situation on any handler e.g. JwtVerifyHandler, it use LightHttpHandler.setExchangeStatus to contstruct error.

We log error on line LightHttpHandler:83, the error includes both json error object and some text content. There are 2 problems, firstly the text context in the message log doesnt give enough info about where this error came from. Secndly this error log message conbines both json and text in one message. Hence this issue if for fixing following 2 problems:
1. Log 2 seperate messages in instead of one. One containing json message and other containing exception stack trace.
2. Log complete stack trace pointing to the origin of problem, instead of just one line.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Split the error log in LightHttpHandler interface into 2 seperate error log statements light-4j master](https://trello.com/c/nlAQ32z8/887-split-the-error-log-in-lighthttphandler-interface-into-2-seperate-error-log-statements-light-4j-master)
