### ISSUE TITLE
logging Status with JSON format

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#874]
logging status info with JSON format instead of Stringified JSON
eg. logger.error("ValidationError:" + status.toString());
status.toString() is pure JSON, but with prefix ValidationError, it cannot be recognized by logging framework.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [logging Status with JSON format light-4j master](https://trello.com/c/pnvr8FCc/902-logging-status-with-json-format-light-4j-master)

**Comment by stevehu** [comment]
For some users, they are using the JSON appenders so that the logs can be injected into Splunk. Mixing string and JSON in the same logging statement will cause issues for those appenders. Thank you @BalloonWen for your help.
