### ISSUE TITLE
auditOnError config is not properly set in LightHttpHandler

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#876]
The handler is trying to get auditOnError and auditStackTrace from handler config, which is incorrect.

**Comment by stevehu** [comment]
It was set in the handler.yml because the code is in the LightHttpHandler that has handler.yml for config. Now, it makes sense to move these two properties to the audit.yml as they are about the audit log. One question, why we are using noCache to load the audit.yml?

**Comment by BalloonWen** [comment]
> It was set in the handler.yml because the code is in the LightHttpHandler that has handler.yml for config. Now, it makes sense to move these two properties to the audit.yml as they are about the audit log. One question, why we are using noCache to load the audit.yml?

if use getJsonObjectConfig, it will return AuditConfig.class  but this handler module is not depend on audit module, so in order to get the Map type config, I use this noCache method.

**Comment by stevehu** [comment]
Got it. Thanks a lot for the explanation.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [auditOnError config is not properly set in LightHttpHandler light-4j master](https://trello.com/c/1Spo1xTR/908-auditonerror-config-is-not-properly-set-in-lighthttphandler-light-4j-master)
