### ISSUE TITLE
proxy when getting oauth key should not be enabled when the value is empty

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#877]
currently in OauthHelper, it will check proxyHost is null or not, but when proxyHost is an empty value, it should also be disabled.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [proxy when getting oauth key should not be enabled when the value is empty light-4j master](https://trello.com/c/d3Hbgio9/905-proxy-when-getting-oauth-key-should-not-be-enabled-when-the-value-is-empty-light-4j-master)
