### ISSUE TITLE
add metadata to Status to support customizing info

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#884]
add a metadata field to Status when send response so that customized info will be added as metadata

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add metadata to Status to support customizing info light-4j master](https://trello.com/c/21OQrEN9/920-add-metadata-to-status-to-support-customizing-info-light-4j-master)

**Comment by stevehu** [comment]
@BalloonWen Could you please update the status document to reflect the changes we have made? Thanks.
