### ISSUE TITLE
show message, description, metadata conditionally

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#894]
1. Showing of message, description, metadata fields in Status is controlled by showMessage, showDescription, showMetadata (was implemented)
2. This feature was implemented in Status.toString() method, which will result logging and responding the same status.
3. There's a requirement in real world makes more sense to have a limited Status response but a more detailed logging of Status.
Thus, showMessage, showDescription, showMetadata will only control the showing for response with setExchangeStatus() method, but not logging. For logging, always log all the info

**Comment by subhamg** [comment]
test

**Comment by subhamg** [comment]
test 1

**Comment by subhamg** [comment]
test 2

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [show message, description, metadata conditionally light-4j master](https://trello.com/c/FnlwlFXb/921-show-message-description-metadata-conditionally-light-4j-master)
