### ISSUE TITLE
add Status error when cannot resolve Oauth key

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#898]
Need add a error status when there's a exception to get the certificate from key, so that the user will easier to track this error by error code instead of a generic Runtime Exception

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add Status error when cannot resolve Oauth key light-4j master](https://trello.com/c/PJKMazDO/925-add-status-error-when-cannot-resolve-oauth-key-light-4j-master)
