### ISSUE TITLE
When mask is turned on, AuditHandler fails to log the request

### ISSUE THREAD

**Issue by jsu216** [networknt/light-4j#935]
When the request body is a valid json object, the BodyHandler converts it to a java object (Map or List).
Since masking cannot be done on the object directly, the AuditHandler converts it to a String first. But it calls the toString() method of the object instead of the reserialize it. The result of the toString() method is not a valid Json format (e.g. missing double quote for key name). So this stops the masking and no audit log recorded.

There is an outstanding issue related to this [#13](https://github.com/networknt/light-4j/issues/13)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When mask is turned on, AuditHandler fails to log the request  light-4j 1.6.x](https://trello.com/c/P3miFowF/1021-when-mask-is-turned-on-audithandler-fails-to-log-the-request-light-4j-16x)
