### ISSUE TITLE
ClassCastException in maskList method

### ISSUE THREAD

**Issue by ssoifer** [networknt/light-4j#942]
https://github.com/networknt/light-4j/blob/9bb900479c9a4fb2a5e7fe036ec61fec5c4e2044/mask/src/main/java/com/networknt/mask/Mask.java#L226

Hello @stevehu @NicholasAzar @BalloonWen @sachin-walia ,
I am having one issue, I am calling to maskJson with payload, lets say something simple as below:
**{"name":"Steve","list":[{"name": "Nick"}, {"name": "Josh"}],"password":"secret"}**
in mask.yml I am giving path: **"$.list.[*].name": "(.*)"** and its working great.
the issue is coming once I am changing the payload to this: 
**{"name":"Steve","list":[{"name": "Josh"}],"password":"secret"}**
meaning, I am sending list with only one item, the path remains.
**in line 226, ctx.read(path) returning just one value, String = "Josh" and then its failing on casting.
List values = ctx.read(path) --> cannot cast string to list.**
is it me doing something wrong? maybe the path should be different in mask.yml? of course  "$.list.[0].name": "(.*)" is working fine, but I have no idea how many items will be sent in the request and I want to mask this field in all the list items.

Thanks.

**Comment by ssoifer** [comment]
Thanks for the response.
I created PR for this:
https://github.com/networknt/light-4j/pull/945

**Comment by ssoifer** [comment]
@stevehu any update on this issue?

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ClassCastException in maskList method light-4j master](https://trello.com/c/JFwLMnOx/1029-classcastexception-in-masklist-method-light-4j-master)

**Comment by miklish** [comment]
@stevehu @jaydeepparekh1311  Comments?
