### ISSUE TITLE
One Potential NPE in RootDumper.java

### ISSUE THREAD

**Issue by containerAnalyzer** [networknt/light-4j#962]
Hello,
Our static analyzer found a following potential NPE. We have checked the feasibility of this execution trace. It is necessary to defend this vulnerability to improve the code quality.

1. Return **null** to caller
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/DumperFactory.java#L97

2. Function **create** executes and stores the return value to **dumper** (dumper can be null)
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/DumperFactory.java#L50

3. Function **add** executes and returns
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/DumperFactory.java#L51

4. Program reaches the return point, modifying one of the elements in **dumpers** to null, where **dumpers** is the return value
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/DumperFactory.java#L53

5. The return value of **dumperFactory.createRequestDumpers** contains **null** as its element
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/RootDumper.java#L47

6. Function **next** executes and store the return value to **dumper** (**dumper** can be **null**)
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/RootDumper.java#L47

7. **dumper** is passed as the **this** pointer to the function **isApplicableForRequest** (**dumper** can be **null**), which will lead to null pointer dereference
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/RootDumper.java#L48

Commit: bdddf0e7c71d502fffbfd0d370b03b6cee26c39e

**Comment by stevehu** [comment]
related to https://github.com/networknt/light-4j/issues/981 and resolve together.
