### ISSUE TITLE
GenericDataSource enhancement to allow to set HikariDataSource other setting values

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#970]
Currently GenericDataSource  set two HikariDataSource  setting

        ds.setMaximumPoolSize((Integer)mainParams.get("maximumPoolSize"));
        ds.setConnectionTimeout((Integer)mainParams.get("connectionTimeout"));

We can enhance the GenericDataSource to allow user set other values, for example:

HikariDataSource setConnectionTestQuery
HikariDataSource setLeakDetectionThreshold
...

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GenericDataSource enhancement to allow to set HikariDataSource other setting values light-4j master](https://trello.com/c/kOl6j7tb/1097-genericdatasource-enhancement-to-allow-to-set-hikaridatasource-other-setting-values-light-4j-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GenericDataSource enhancement to allow to set HikariDataSource other setting values light-4j 1.6.x](https://trello.com/c/D8O1l88G/1098-genericdatasource-enhancement-to-allow-to-set-hikaridatasource-other-setting-values-light-4j-16x)
