### ISSUE TITLE
Another NPE in RootDumper.java

### ISSUE THREAD

**Issue by containerAnalyzer** [networknt/light-4j#981]
Hello,
Our static analyzer found a following potential NPE. We have checked the feasibility of this execution trace. It is necessary to defend this vulnerability to improve the code quality.
Here is the bug trace.

1. Return **null** to caller 
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/DumperFactory.java#L125

2. Function **create** executes and stores the return value to **dumper** (**dumper** can be **null**)
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/DumperFactory.java#L66

3. Function **add** executes and **dumpers** contains **null**
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/DumperFactory.java#L67

4. Program reaches the return point, return **dumpers**
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/DumperFactory.java#L69

5. Function **createResponseDumpers** executes and returns
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/RootDumper.java#L63

6. Function **next** executes and stores the return value to **dumper** (**dumper** can be **null**)
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/RootDumper.java#L63

7. **dumper** is passed as the this pointer to function **isApplicableForResponse** (**dumper** can be **null**), which will leak to null pointer dereference
https://github.com/networknt/light-4j/blob/bdddf0e7c71d502fffbfd0d370b03b6cee26c39e/dump/src/main/java/com/networknt/dump/RootDumper.java#L64

Commit: bdddf0e7c71d502fffbfd0d370b03b6cee26c39e

ContainerAnalyzer

**Comment by stevehu** [comment]
@containerAnalyzer Thanks for raising the issue. It makes sense to prevent the NPE in these classes. Is your tool capable issue a PR to get the issues fixed? Thanks.

**Comment by containerAnalyzer** [comment]
I will submit the PR manually later. By the way, Issue #962 is also caused by this class. I think these two NPEs can be fixed by a single PR.

**Comment by stevehu** [comment]
Yes. It is a good idea to put them into one PR.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Another NPE in RootDumper.java light-4j master](https://trello.com/c/PM7vHH54/1110-another-npe-in-rootdumperjava-light-4j-master)

**Comment by stevehu** [comment]
@containerAnalyzer Thanks for the PR to resolve the issue.
