### ISSUE TITLE
ingress-proxy config file put in wrong resource folder

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#984]
The config file (proxy.yaml) for ingress-proxy added to wrong resource folder and it can not be extended

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ingress-proxy config file put in wrong resource folder light-4j master](https://trello.com/c/mFjEeni1/1102-ingress-proxy-config-file-put-in-wrong-resource-folder-light-4j-master)
