### ISSUE TITLE
Add default token.yaml config file to egress-router module

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#995]
Add default token.yaml config file to egress-router module for handlers:

TokenHandler

SAMLTokenHandler

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add default token.yaml config file to egress-router module light-4j master](https://trello.com/c/CjKeueIU/1119-add-default-tokenyaml-config-file-to-egress-router-module-light-4j-master)
